/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _lib_auth from "../_lib/auth.js";
import type * as _lib_functions from "../_lib/functions.js";
import type * as _lib_refusal from "../_lib/refusal.js";
import type * as _lib_socialProviders from "../_lib/socialProviders.js";
import type * as _lib_softDelete from "../_lib/softDelete.js";
import type * as _lib_text from "../_lib/text.js";
import type * as _lib_time from "../_lib/time.js";
import type * as _lib_validators_access from "../_lib/validators/access.js";
import type * as _lib_validators_activities from "../_lib/validators/activities.js";
import type * as _lib_validators_addressFormats from "../_lib/validators/addressFormats.js";
import type * as _lib_validators_apiKeys from "../_lib/validators/apiKeys.js";
import type * as _lib_validators_appConfig from "../_lib/validators/appConfig.js";
import type * as _lib_validators_attachments from "../_lib/validators/attachments.js";
import type * as _lib_validators_auditLogs from "../_lib/validators/auditLogs.js";
import type * as _lib_validators_companies from "../_lib/validators/companies.js";
import type * as _lib_validators_companyRegistry from "../_lib/validators/companyRegistry.js";
import type * as _lib_validators_connectors from "../_lib/validators/connectors.js";
import type * as _lib_validators_crm from "../_lib/validators/crm.js";
import type * as _lib_validators_deals from "../_lib/validators/deals.js";
import type * as _lib_validators_duplicates from "../_lib/validators/duplicates.js";
import type * as _lib_validators_employees from "../_lib/validators/employees.js";
import type * as _lib_validators_fields from "../_lib/validators/fields.js";
import type * as _lib_validators_filters from "../_lib/validators/filters.js";
import type * as _lib_validators_forms from "../_lib/validators/forms.js";
import type * as _lib_validators_imports from "../_lib/validators/imports.js";
import type * as _lib_validators_invitations from "../_lib/validators/invitations.js";
import type * as _lib_validators_landingPages from "../_lib/validators/landingPages.js";
import type * as _lib_validators_leadLists from "../_lib/validators/leadLists.js";
import type * as _lib_validators_lifecycle from "../_lib/validators/lifecycle.js";
import type * as _lib_validators_properties from "../_lib/validators/properties.js";
import type * as _lib_validators_propertyTypes from "../_lib/validators/propertyTypes.js";
import type * as _lib_validators_retention from "../_lib/validators/retention.js";
import type * as _lib_validators_rgpd from "../_lib/validators/rgpd.js";
import type * as _lib_validators_roles from "../_lib/validators/roles.js";
import type * as _lib_validators_scoring from "../_lib/validators/scoring.js";
import type * as _lib_validators_shared from "../_lib/validators/shared.js";
import type * as _lib_validators_teams from "../_lib/validators/teams.js";
import type * as _lib_validators_timeline from "../_lib/validators/timeline.js";
import type * as _lib_validators_tracking from "../_lib/validators/tracking.js";
import type * as _lib_validators_users from "../_lib/validators/users.js";
import type * as _lib_validators_workflowSteps from "../_lib/validators/workflowSteps.js";
import type * as _lib_validators_workflows from "../_lib/validators/workflows.js";
import type * as auth from "../auth.js";
import type * as auth_emailTemplates from "../auth/emailTemplates.js";
import type * as crons from "../crons.js";
import type * as extensions from "../extensions.js";
import type * as extensionsSchema from "../extensionsSchema.js";
import type * as features_activities_mutations from "../features/activities/mutations.js";
import type * as features_activities_queries from "../features/activities/queries.js";
import type * as features_api_internal from "../features/api/internal.js";
import type * as features_api_mutations from "../features/api/mutations.js";
import type * as features_api_queries from "../features/api/queries.js";
import type * as features_api_routes from "../features/api/routes.js";
import type * as features_api_writes from "../features/api/writes.js";
import type * as features_attachments_internal from "../features/attachments/internal.js";
import type * as features_attachments_mutations from "../features/attachments/mutations.js";
import type * as features_attachments_queries from "../features/attachments/queries.js";
import type * as features_campaigns_actions from "../features/campaigns/actions.js";
import type * as features_campaigns_internal from "../features/campaigns/internal.js";
import type * as features_campaigns_mutations from "../features/campaigns/mutations.js";
import type * as features_campaigns_queries from "../features/campaigns/queries.js";
import type * as features_campaigns_routes from "../features/campaigns/routes.js";
import type * as features_companies_actions from "../features/companies/actions.js";
import type * as features_companies_internal from "../features/companies/internal.js";
import type * as features_companies_mutations from "../features/companies/mutations.js";
import type * as features_companies_queries from "../features/companies/queries.js";
import type * as features_config_internal from "../features/config/internal.js";
import type * as features_config_mutations from "../features/config/mutations.js";
import type * as features_config_queries from "../features/config/queries.js";
import type * as features_connectors_actions from "../features/connectors/actions.js";
import type * as features_connectors_internal from "../features/connectors/internal.js";
import type * as features_connectors_mutations from "../features/connectors/mutations.js";
import type * as features_connectors_queries from "../features/connectors/queries.js";
import type * as features_connectors_routes from "../features/connectors/routes.js";
import type * as features_consent_mutations from "../features/consent/mutations.js";
import type * as features_consent_queries from "../features/consent/queries.js";
import type * as features_deals_mutations from "../features/deals/mutations.js";
import type * as features_deals_queries from "../features/deals/queries.js";
import type * as features_duplicates_internal from "../features/duplicates/internal.js";
import type * as features_duplicates_mutations from "../features/duplicates/mutations.js";
import type * as features_duplicates_queries from "../features/duplicates/queries.js";
import type * as features_email_actions from "../features/email/actions.js";
import type * as features_email_send from "../features/email/send.js";
import type * as features_forms_internal from "../features/forms/internal.js";
import type * as features_forms_mutations from "../features/forms/mutations.js";
import type * as features_forms_queries from "../features/forms/queries.js";
import type * as features_forms_routes from "../features/forms/routes.js";
import type * as features_imports_actions from "../features/imports/actions.js";
import type * as features_imports_entities_activities from "../features/imports/entities/activities.js";
import type * as features_imports_entities_companies from "../features/imports/entities/companies.js";
import type * as features_imports_entities_contact from "../features/imports/entities/contact.js";
import type * as features_imports_entities_deals from "../features/imports/entities/deals.js";
import type * as features_imports_entities_index from "../features/imports/entities/index.js";
import type * as features_imports_entities_leads from "../features/imports/entities/leads.js";
import type * as features_imports_entities_types from "../features/imports/entities/types.js";
import type * as features_imports_internal from "../features/imports/internal.js";
import type * as features_imports_lib from "../features/imports/lib.js";
import type * as features_imports_mutations from "../features/imports/mutations.js";
import type * as features_imports_queries from "../features/imports/queries.js";
import type * as features_invitations_internal from "../features/invitations/internal.js";
import type * as features_invitations_mutations from "../features/invitations/mutations.js";
import type * as features_invitations_queries from "../features/invitations/queries.js";
import type * as features_landingPages_internal from "../features/landingPages/internal.js";
import type * as features_landingPages_mutations from "../features/landingPages/mutations.js";
import type * as features_landingPages_queries from "../features/landingPages/queries.js";
import type * as features_landingPages_routes from "../features/landingPages/routes.js";
import type * as features_leadLists_internal from "../features/leadLists/internal.js";
import type * as features_leadLists_mutations from "../features/leadLists/mutations.js";
import type * as features_leadLists_queries from "../features/leadLists/queries.js";
import type * as features_leads_mutations from "../features/leads/mutations.js";
import type * as features_leads_queries from "../features/leads/queries.js";
import type * as features_practitionerInfo_actions from "../features/practitionerInfo/actions.js";
import type * as features_properties_mutations from "../features/properties/mutations.js";
import type * as features_properties_queries from "../features/properties/queries.js";
import type * as features_retention_internal from "../features/retention/internal.js";
import type * as features_retention_queries from "../features/retention/queries.js";
import type * as features_rgpd_actions from "../features/rgpd/actions.js";
import type * as features_rgpd_internal from "../features/rgpd/internal.js";
import type * as features_rgpd_mutations from "../features/rgpd/mutations.js";
import type * as features_rgpd_queries from "../features/rgpd/queries.js";
import type * as features_roles_mutations from "../features/roles/mutations.js";
import type * as features_roles_queries from "../features/roles/queries.js";
import type * as features_scoring_internal from "../features/scoring/internal.js";
import type * as features_scoring_mutations from "../features/scoring/mutations.js";
import type * as features_scoring_queries from "../features/scoring/queries.js";
import type * as features_teams_mutations from "../features/teams/mutations.js";
import type * as features_teams_queries from "../features/teams/queries.js";
import type * as features_timeline_queries from "../features/timeline/queries.js";
import type * as features_tracking_internal from "../features/tracking/internal.js";
import type * as features_tracking_queries from "../features/tracking/queries.js";
import type * as features_tracking_routes from "../features/tracking/routes.js";
import type * as features_users_mutations from "../features/users/mutations.js";
import type * as features_users_queries from "../features/users/queries.js";
import type * as features_workflows_actions from "../features/workflows/actions.js";
import type * as features_workflows_internal from "../features/workflows/internal.js";
import type * as features_workflows_mutations from "../features/workflows/mutations.js";
import type * as features_workflows_queries from "../features/workflows/queries.js";
import type * as http from "../http.js";
import type * as lib_activities_aggregates from "../lib/activities/aggregates.js";
import type * as lib_activities_records from "../lib/activities/records.js";
import type * as lib_addresses_validation from "../lib/addresses/validation.js";
import type * as lib_api_auth from "../lib/api/auth.js";
import type * as lib_api_bodies from "../lib/api/bodies.js";
import type * as lib_api_dtos from "../lib/api/dtos.js";
import type * as lib_api_errors from "../lib/api/errors.js";
import type * as lib_api_http from "../lib/api/http.js";
import type * as lib_api_routeTable from "../lib/api/routeTable.js";
import type * as lib_api_writes_activities from "../lib/api/writes/activities.js";
import type * as lib_api_writes_common from "../lib/api/writes/common.js";
import type * as lib_api_writes_companies from "../lib/api/writes/companies.js";
import type * as lib_api_writes_contacts from "../lib/api/writes/contacts.js";
import type * as lib_api_writes_deals from "../lib/api/writes/deals.js";
import type * as lib_attachments_storage from "../lib/attachments/storage.js";
import type * as lib_audit_log from "../lib/audit/log.js";
import type * as lib_campaigns_events from "../lib/campaigns/events.js";
import type * as lib_campaigns_links from "../lib/campaigns/links.js";
import type * as lib_campaigns_params from "../lib/campaigns/params.js";
import type * as lib_campaigns_prepare from "../lib/campaigns/prepare.js";
import type * as lib_campaigns_resend from "../lib/campaigns/resend.js";
import type * as lib_campaigns_stats from "../lib/campaigns/stats.js";
import type * as lib_companies_aggregates from "../lib/companies/aggregates.js";
import type * as lib_companies_domains from "../lib/companies/domains.js";
import type * as lib_companies_lookup from "../lib/companies/lookup.js";
import type * as lib_companies_search from "../lib/companies/search.js";
import type * as lib_config_appUrl from "../lib/config/appUrl.js";
import type * as lib_config_settings from "../lib/config/settings.js";
import type * as lib_connectors_oauth from "../lib/connectors/oauth.js";
import type * as lib_deals_aggregates from "../lib/deals/aggregates.js";
import type * as lib_deals_records from "../lib/deals/records.js";
import type * as lib_duplicates_detection from "../lib/duplicates/detection.js";
import type * as lib_email_brevo from "../lib/email/brevo.js";
import type * as lib_email_provider from "../lib/email/provider.js";
import type * as lib_email_smtp from "../lib/email/smtp.js";
import type * as lib_extensions_gates from "../lib/extensions/gates.js";
import type * as lib_extensions_observers from "../lib/extensions/observers.js";
import type * as lib_extensions_types from "../lib/extensions/types.js";
import type * as lib_filters_matching from "../lib/filters/matching.js";
import type * as lib_forms_embed from "../lib/forms/embed.js";
import type * as lib_forms_submission from "../lib/forms/submission.js";
import type * as lib_http_body from "../lib/http/body.js";
import type * as lib_http_cors from "../lib/http/cors.js";
import type * as lib_invitations_pending from "../lib/invitations/pending.js";
import type * as lib_landingPages_pages from "../lib/landingPages/pages.js";
import type * as lib_landingPages_render from "../lib/landingPages/render.js";
import type * as lib_landingPages_stats from "../lib/landingPages/stats.js";
import type * as lib_leadLists_dynamic from "../lib/leadLists/dynamic.js";
import type * as lib_leadLists_members from "../lib/leadLists/members.js";
import type * as lib_leads_aggregates from "../lib/leads/aggregates.js";
import type * as lib_leads_change from "../lib/leads/change.js";
import type * as lib_leads_import from "../lib/leads/import.js";
import type * as lib_leads_lifecycle from "../lib/leads/lifecycle.js";
import type * as lib_leads_matching from "../lib/leads/matching.js";
import type * as lib_leads_notes from "../lib/leads/notes.js";
import type * as lib_leads_records from "../lib/leads/records.js";
import type * as lib_leads_search from "../lib/leads/search.js";
import type * as lib_leads_signals from "../lib/leads/signals.js";
import type * as lib_leads_tableFilters from "../lib/leads/tableFilters.js";
import type * as lib_leads_targets from "../lib/leads/targets.js";
import type * as lib_properties_definitions from "../lib/properties/definitions.js";
import type * as lib_retention_budget from "../lib/retention/budget.js";
import type * as lib_retention_purge from "../lib/retention/purge.js";
import type * as lib_retention_rows from "../lib/retention/rows.js";
import type * as lib_rgpd_access from "../lib/rgpd/access.js";
import type * as lib_roles_access from "../lib/roles/access.js";
import type * as lib_roles_visibility from "../lib/roles/visibility.js";
import type * as lib_scoring_score from "../lib/scoring/score.js";
import type * as lib_security_crypto from "../lib/security/crypto.js";
import type * as lib_security_encoding from "../lib/security/encoding.js";
import type * as lib_security_rateLimits from "../lib/security/rateLimits.js";
import type * as lib_shared_aggregates from "../lib/shared/aggregates.js";
import type * as lib_shared_db from "../lib/shared/db.js";
import type * as lib_shared_devWhitelist from "../lib/shared/devWhitelist.js";
import type * as lib_shared_docs from "../lib/shared/docs.js";
import type * as lib_sms_brevo from "../lib/sms/brevo.js";
import type * as lib_timeline_events from "../lib/timeline/events.js";
import type * as lib_timeline_pagination from "../lib/timeline/pagination.js";
import type * as lib_timeline_sources from "../lib/timeline/sources.js";
import type * as lib_tracking_beacon from "../lib/tracking/beacon.js";
import type * as lib_tracking_config from "../lib/tracking/config.js";
import type * as lib_tracking_script from "../lib/tracking/script.js";
import type * as lib_tracking_views from "../lib/tracking/views.js";
import type * as lib_users_owners from "../lib/users/owners.js";
import type * as lib_users_serialize from "../lib/users/serialize.js";
import type * as lib_workflows_activation from "../lib/workflows/activation.js";
import type * as lib_workflows_dispatch from "../lib/workflows/dispatch.js";
import type * as lib_workflows_params from "../lib/workflows/params.js";
import type * as lib_workflows_rules from "../lib/workflows/rules.js";
import type * as lib_workflows_runs from "../lib/workflows/runs.js";
import type * as lib_workflows_steps_deals from "../lib/workflows/steps/deals.js";
import type * as lib_workflows_steps_flow from "../lib/workflows/steps/flow.js";
import type * as lib_workflows_steps_lead from "../lib/workflows/steps/lead.js";
import type * as lib_workflows_steps_lists from "../lib/workflows/steps/lists.js";
import type * as lib_workflows_steps_sends from "../lib/workflows/steps/sends.js";
import type * as lib_workflows_steps_tasks from "../lib/workflows/steps/tasks.js";
import type * as migrations from "../migrations.js";
import type * as seed_devEmployee from "../seed/devEmployee.js";
import type * as setup_helpers from "../setup/helpers.js";
import type * as setup_mutations from "../setup/mutations.js";
import type * as setup_queries from "../setup/queries.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "_lib/auth": typeof _lib_auth;
  "_lib/functions": typeof _lib_functions;
  "_lib/refusal": typeof _lib_refusal;
  "_lib/socialProviders": typeof _lib_socialProviders;
  "_lib/softDelete": typeof _lib_softDelete;
  "_lib/text": typeof _lib_text;
  "_lib/time": typeof _lib_time;
  "_lib/validators/access": typeof _lib_validators_access;
  "_lib/validators/activities": typeof _lib_validators_activities;
  "_lib/validators/addressFormats": typeof _lib_validators_addressFormats;
  "_lib/validators/apiKeys": typeof _lib_validators_apiKeys;
  "_lib/validators/appConfig": typeof _lib_validators_appConfig;
  "_lib/validators/attachments": typeof _lib_validators_attachments;
  "_lib/validators/auditLogs": typeof _lib_validators_auditLogs;
  "_lib/validators/companies": typeof _lib_validators_companies;
  "_lib/validators/companyRegistry": typeof _lib_validators_companyRegistry;
  "_lib/validators/connectors": typeof _lib_validators_connectors;
  "_lib/validators/crm": typeof _lib_validators_crm;
  "_lib/validators/deals": typeof _lib_validators_deals;
  "_lib/validators/duplicates": typeof _lib_validators_duplicates;
  "_lib/validators/employees": typeof _lib_validators_employees;
  "_lib/validators/fields": typeof _lib_validators_fields;
  "_lib/validators/filters": typeof _lib_validators_filters;
  "_lib/validators/forms": typeof _lib_validators_forms;
  "_lib/validators/imports": typeof _lib_validators_imports;
  "_lib/validators/invitations": typeof _lib_validators_invitations;
  "_lib/validators/landingPages": typeof _lib_validators_landingPages;
  "_lib/validators/leadLists": typeof _lib_validators_leadLists;
  "_lib/validators/lifecycle": typeof _lib_validators_lifecycle;
  "_lib/validators/properties": typeof _lib_validators_properties;
  "_lib/validators/propertyTypes": typeof _lib_validators_propertyTypes;
  "_lib/validators/retention": typeof _lib_validators_retention;
  "_lib/validators/rgpd": typeof _lib_validators_rgpd;
  "_lib/validators/roles": typeof _lib_validators_roles;
  "_lib/validators/scoring": typeof _lib_validators_scoring;
  "_lib/validators/shared": typeof _lib_validators_shared;
  "_lib/validators/teams": typeof _lib_validators_teams;
  "_lib/validators/timeline": typeof _lib_validators_timeline;
  "_lib/validators/tracking": typeof _lib_validators_tracking;
  "_lib/validators/users": typeof _lib_validators_users;
  "_lib/validators/workflowSteps": typeof _lib_validators_workflowSteps;
  "_lib/validators/workflows": typeof _lib_validators_workflows;
  auth: typeof auth;
  "auth/emailTemplates": typeof auth_emailTemplates;
  crons: typeof crons;
  extensions: typeof extensions;
  extensionsSchema: typeof extensionsSchema;
  "features/activities/mutations": typeof features_activities_mutations;
  "features/activities/queries": typeof features_activities_queries;
  "features/api/internal": typeof features_api_internal;
  "features/api/mutations": typeof features_api_mutations;
  "features/api/queries": typeof features_api_queries;
  "features/api/routes": typeof features_api_routes;
  "features/api/writes": typeof features_api_writes;
  "features/attachments/internal": typeof features_attachments_internal;
  "features/attachments/mutations": typeof features_attachments_mutations;
  "features/attachments/queries": typeof features_attachments_queries;
  "features/campaigns/actions": typeof features_campaigns_actions;
  "features/campaigns/internal": typeof features_campaigns_internal;
  "features/campaigns/mutations": typeof features_campaigns_mutations;
  "features/campaigns/queries": typeof features_campaigns_queries;
  "features/campaigns/routes": typeof features_campaigns_routes;
  "features/companies/actions": typeof features_companies_actions;
  "features/companies/internal": typeof features_companies_internal;
  "features/companies/mutations": typeof features_companies_mutations;
  "features/companies/queries": typeof features_companies_queries;
  "features/config/internal": typeof features_config_internal;
  "features/config/mutations": typeof features_config_mutations;
  "features/config/queries": typeof features_config_queries;
  "features/connectors/actions": typeof features_connectors_actions;
  "features/connectors/internal": typeof features_connectors_internal;
  "features/connectors/mutations": typeof features_connectors_mutations;
  "features/connectors/queries": typeof features_connectors_queries;
  "features/connectors/routes": typeof features_connectors_routes;
  "features/consent/mutations": typeof features_consent_mutations;
  "features/consent/queries": typeof features_consent_queries;
  "features/deals/mutations": typeof features_deals_mutations;
  "features/deals/queries": typeof features_deals_queries;
  "features/duplicates/internal": typeof features_duplicates_internal;
  "features/duplicates/mutations": typeof features_duplicates_mutations;
  "features/duplicates/queries": typeof features_duplicates_queries;
  "features/email/actions": typeof features_email_actions;
  "features/email/send": typeof features_email_send;
  "features/forms/internal": typeof features_forms_internal;
  "features/forms/mutations": typeof features_forms_mutations;
  "features/forms/queries": typeof features_forms_queries;
  "features/forms/routes": typeof features_forms_routes;
  "features/imports/actions": typeof features_imports_actions;
  "features/imports/entities/activities": typeof features_imports_entities_activities;
  "features/imports/entities/companies": typeof features_imports_entities_companies;
  "features/imports/entities/contact": typeof features_imports_entities_contact;
  "features/imports/entities/deals": typeof features_imports_entities_deals;
  "features/imports/entities/index": typeof features_imports_entities_index;
  "features/imports/entities/leads": typeof features_imports_entities_leads;
  "features/imports/entities/types": typeof features_imports_entities_types;
  "features/imports/internal": typeof features_imports_internal;
  "features/imports/lib": typeof features_imports_lib;
  "features/imports/mutations": typeof features_imports_mutations;
  "features/imports/queries": typeof features_imports_queries;
  "features/invitations/internal": typeof features_invitations_internal;
  "features/invitations/mutations": typeof features_invitations_mutations;
  "features/invitations/queries": typeof features_invitations_queries;
  "features/landingPages/internal": typeof features_landingPages_internal;
  "features/landingPages/mutations": typeof features_landingPages_mutations;
  "features/landingPages/queries": typeof features_landingPages_queries;
  "features/landingPages/routes": typeof features_landingPages_routes;
  "features/leadLists/internal": typeof features_leadLists_internal;
  "features/leadLists/mutations": typeof features_leadLists_mutations;
  "features/leadLists/queries": typeof features_leadLists_queries;
  "features/leads/mutations": typeof features_leads_mutations;
  "features/leads/queries": typeof features_leads_queries;
  "features/practitionerInfo/actions": typeof features_practitionerInfo_actions;
  "features/properties/mutations": typeof features_properties_mutations;
  "features/properties/queries": typeof features_properties_queries;
  "features/retention/internal": typeof features_retention_internal;
  "features/retention/queries": typeof features_retention_queries;
  "features/rgpd/actions": typeof features_rgpd_actions;
  "features/rgpd/internal": typeof features_rgpd_internal;
  "features/rgpd/mutations": typeof features_rgpd_mutations;
  "features/rgpd/queries": typeof features_rgpd_queries;
  "features/roles/mutations": typeof features_roles_mutations;
  "features/roles/queries": typeof features_roles_queries;
  "features/scoring/internal": typeof features_scoring_internal;
  "features/scoring/mutations": typeof features_scoring_mutations;
  "features/scoring/queries": typeof features_scoring_queries;
  "features/teams/mutations": typeof features_teams_mutations;
  "features/teams/queries": typeof features_teams_queries;
  "features/timeline/queries": typeof features_timeline_queries;
  "features/tracking/internal": typeof features_tracking_internal;
  "features/tracking/queries": typeof features_tracking_queries;
  "features/tracking/routes": typeof features_tracking_routes;
  "features/users/mutations": typeof features_users_mutations;
  "features/users/queries": typeof features_users_queries;
  "features/workflows/actions": typeof features_workflows_actions;
  "features/workflows/internal": typeof features_workflows_internal;
  "features/workflows/mutations": typeof features_workflows_mutations;
  "features/workflows/queries": typeof features_workflows_queries;
  http: typeof http;
  "lib/activities/aggregates": typeof lib_activities_aggregates;
  "lib/activities/records": typeof lib_activities_records;
  "lib/addresses/validation": typeof lib_addresses_validation;
  "lib/api/auth": typeof lib_api_auth;
  "lib/api/bodies": typeof lib_api_bodies;
  "lib/api/dtos": typeof lib_api_dtos;
  "lib/api/errors": typeof lib_api_errors;
  "lib/api/http": typeof lib_api_http;
  "lib/api/routeTable": typeof lib_api_routeTable;
  "lib/api/writes/activities": typeof lib_api_writes_activities;
  "lib/api/writes/common": typeof lib_api_writes_common;
  "lib/api/writes/companies": typeof lib_api_writes_companies;
  "lib/api/writes/contacts": typeof lib_api_writes_contacts;
  "lib/api/writes/deals": typeof lib_api_writes_deals;
  "lib/attachments/storage": typeof lib_attachments_storage;
  "lib/audit/log": typeof lib_audit_log;
  "lib/campaigns/events": typeof lib_campaigns_events;
  "lib/campaigns/links": typeof lib_campaigns_links;
  "lib/campaigns/params": typeof lib_campaigns_params;
  "lib/campaigns/prepare": typeof lib_campaigns_prepare;
  "lib/campaigns/resend": typeof lib_campaigns_resend;
  "lib/campaigns/stats": typeof lib_campaigns_stats;
  "lib/companies/aggregates": typeof lib_companies_aggregates;
  "lib/companies/domains": typeof lib_companies_domains;
  "lib/companies/lookup": typeof lib_companies_lookup;
  "lib/companies/search": typeof lib_companies_search;
  "lib/config/appUrl": typeof lib_config_appUrl;
  "lib/config/settings": typeof lib_config_settings;
  "lib/connectors/oauth": typeof lib_connectors_oauth;
  "lib/deals/aggregates": typeof lib_deals_aggregates;
  "lib/deals/records": typeof lib_deals_records;
  "lib/duplicates/detection": typeof lib_duplicates_detection;
  "lib/email/brevo": typeof lib_email_brevo;
  "lib/email/provider": typeof lib_email_provider;
  "lib/email/smtp": typeof lib_email_smtp;
  "lib/extensions/gates": typeof lib_extensions_gates;
  "lib/extensions/observers": typeof lib_extensions_observers;
  "lib/extensions/types": typeof lib_extensions_types;
  "lib/filters/matching": typeof lib_filters_matching;
  "lib/forms/embed": typeof lib_forms_embed;
  "lib/forms/submission": typeof lib_forms_submission;
  "lib/http/body": typeof lib_http_body;
  "lib/http/cors": typeof lib_http_cors;
  "lib/invitations/pending": typeof lib_invitations_pending;
  "lib/landingPages/pages": typeof lib_landingPages_pages;
  "lib/landingPages/render": typeof lib_landingPages_render;
  "lib/landingPages/stats": typeof lib_landingPages_stats;
  "lib/leadLists/dynamic": typeof lib_leadLists_dynamic;
  "lib/leadLists/members": typeof lib_leadLists_members;
  "lib/leads/aggregates": typeof lib_leads_aggregates;
  "lib/leads/change": typeof lib_leads_change;
  "lib/leads/import": typeof lib_leads_import;
  "lib/leads/lifecycle": typeof lib_leads_lifecycle;
  "lib/leads/matching": typeof lib_leads_matching;
  "lib/leads/notes": typeof lib_leads_notes;
  "lib/leads/records": typeof lib_leads_records;
  "lib/leads/search": typeof lib_leads_search;
  "lib/leads/signals": typeof lib_leads_signals;
  "lib/leads/tableFilters": typeof lib_leads_tableFilters;
  "lib/leads/targets": typeof lib_leads_targets;
  "lib/properties/definitions": typeof lib_properties_definitions;
  "lib/retention/budget": typeof lib_retention_budget;
  "lib/retention/purge": typeof lib_retention_purge;
  "lib/retention/rows": typeof lib_retention_rows;
  "lib/rgpd/access": typeof lib_rgpd_access;
  "lib/roles/access": typeof lib_roles_access;
  "lib/roles/visibility": typeof lib_roles_visibility;
  "lib/scoring/score": typeof lib_scoring_score;
  "lib/security/crypto": typeof lib_security_crypto;
  "lib/security/encoding": typeof lib_security_encoding;
  "lib/security/rateLimits": typeof lib_security_rateLimits;
  "lib/shared/aggregates": typeof lib_shared_aggregates;
  "lib/shared/db": typeof lib_shared_db;
  "lib/shared/devWhitelist": typeof lib_shared_devWhitelist;
  "lib/shared/docs": typeof lib_shared_docs;
  "lib/sms/brevo": typeof lib_sms_brevo;
  "lib/timeline/events": typeof lib_timeline_events;
  "lib/timeline/pagination": typeof lib_timeline_pagination;
  "lib/timeline/sources": typeof lib_timeline_sources;
  "lib/tracking/beacon": typeof lib_tracking_beacon;
  "lib/tracking/config": typeof lib_tracking_config;
  "lib/tracking/script": typeof lib_tracking_script;
  "lib/tracking/views": typeof lib_tracking_views;
  "lib/users/owners": typeof lib_users_owners;
  "lib/users/serialize": typeof lib_users_serialize;
  "lib/workflows/activation": typeof lib_workflows_activation;
  "lib/workflows/dispatch": typeof lib_workflows_dispatch;
  "lib/workflows/params": typeof lib_workflows_params;
  "lib/workflows/rules": typeof lib_workflows_rules;
  "lib/workflows/runs": typeof lib_workflows_runs;
  "lib/workflows/steps/deals": typeof lib_workflows_steps_deals;
  "lib/workflows/steps/flow": typeof lib_workflows_steps_flow;
  "lib/workflows/steps/lead": typeof lib_workflows_steps_lead;
  "lib/workflows/steps/lists": typeof lib_workflows_steps_lists;
  "lib/workflows/steps/sends": typeof lib_workflows_steps_sends;
  "lib/workflows/steps/tasks": typeof lib_workflows_steps_tasks;
  migrations: typeof migrations;
  "seed/devEmployee": typeof seed_devEmployee;
  "setup/helpers": typeof setup_helpers;
  "setup/mutations": typeof setup_mutations;
  "setup/queries": typeof setup_queries;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  leadListMemberCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"leadListMemberCounts">;
  leadsByOwner: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"leadsByOwner">;
  leadsByLifecycle: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"leadsByLifecycle">;
  companiesTotal: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"companiesTotal">;
  leadsByCompany: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"leadsByCompany">;
  dealsByStage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"dealsByStage">;
  dealsByPipelineStatus: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"dealsByPipelineStatus">;
  activitiesByOwner: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"activitiesByOwner">;
  activitiesByTeam: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"activitiesByTeam">;
  companiesByOwner: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"companiesByOwner">;
  dealsByOwnerStage: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"dealsByOwnerStage">;
  dealsByOwnerStatus: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"dealsByOwnerStatus">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
};
