// GENERATED FILE — do not edit. Run `bun run scripts/generate-address-formats.ts`.
// Source: Google libaddressinput metadata (https://github.com/google/libaddressinput),
// Apache License 2.0. Field semantics: see addressFormats.ts.
import type { AddressFormatData } from './addressFormats';

export const ADDRESS_FORMAT_DATA: Record<string, AddressFormatData> = {
  AC: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: 'ASCN 1ZZ',
    zipex: 'ASCN 1ZZ',
  },
  AD: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: 'AD[1-7]0\\d',
    zipex: 'AD100',
    regions: [
      ["Parròquia d'Andorra la Vella", 'Andorra la Vella'],
      ['Canillo', 'Canillo'],
      ['Encamp', 'Encamp'],
      ['Escaldes-Engordany', 'Escaldes-Engordany'],
      ['La Massana', 'La Massana'],
      ['Ordino', 'Ordino'],
      ['Sant Julià de Lòria', 'Sant Julià de Lòria'],
    ],
  },
  AE: {
    fmt: '%N%n%O%n%A%n%S',
    lfmt: '%N%n%O%n%A%n%S',
    require: 'AS',
    regionType: 'emirate',
    regions: [
      ['أبو ظبي', 'Abu Dhabi'],
      ['إمارة الشارقةّ', 'Sharjah'],
      ['الفجيرة', 'Fujairah'],
      ['ام القيوين', 'Umm Al Quwain'],
      ['إمارة دبيّ', 'Dubai'],
      ['إمارة رأس الخيمة', 'Ras al Khaimah'],
      ['عجمان', 'Ajman'],
    ],
  },
  AF: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: '\\d{4}',
    zipex: '1001',
  },
  AG: {
    require: 'A',
  },
  AI: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: '(?:AI-)?2640',
    zipex: '2640',
  },
  AL: {
    fmt: '%N%n%O%n%A%n%Z%n%C',
    zip: '\\d{4}',
    zipex: '1001',
  },
  AM: {
    fmt: '%N%n%O%n%A%n%Z%n%C%n%S',
    lfmt: '%N%n%O%n%A%n%Z%n%C%n%S',
    zip: '(?:37)?\\d{4}',
    zipex: '375010',
    regions: [
      ['Արագածոտն', 'Aragatsotn'],
      ['Արարատ', 'Ararat'],
      ['Արմավիր', 'Armavir'],
      ['Գեղարքունիք', 'Gegharkunik'],
      ['Երևան', 'Yerevan'],
      ['Լոռի', 'Lori'],
      ['Կոտայք', 'Kotayk'],
      ['Շիրակ', 'Shirak'],
      ['Սյունիք', 'Syunik'],
      ['Վայոց ձոր', 'Vayots Dzor'],
      ['Տավուշ', 'Tavush'],
    ],
  },
  AO: {},
  AR: {
    fmt: '%N%n%O%n%A%n%Z %C%n%S',
    upper: 'ACZ',
    zip: '[A-HJ-NP-Z]\\d{4}[A-Z]{3}',
    zipex: 'C1070AAM',
    regions: [
      ['Buenos Aires', 'Buenos Aires'],
      ['Catamarca', 'Catamarca'],
      ['Chaco', 'Chaco'],
      ['Chubut', 'Chubut'],
      ['Ciudad Autónoma de Buenos Aires', 'Ciudad Autónoma de Buenos Aires'],
      ['Córdoba', 'Córdoba'],
      ['Corrientes', 'Corrientes'],
      ['Entre Ríos', 'Entre Ríos'],
      ['Formosa', 'Formosa'],
      ['Jujuy', 'Jujuy'],
      ['La Pampa', 'La Pampa'],
      ['La Rioja', 'La Rioja'],
      ['Mendoza', 'Mendoza'],
      ['Misiones', 'Misiones'],
      ['Neuquén', 'Neuquén'],
      ['Río Negro', 'Río Negro'],
      ['Salta', 'Salta'],
      ['San Juan', 'San Juan'],
      ['San Luis', 'San Luis'],
      ['Santa Cruz', 'Santa Cruz'],
      ['Santa Fe', 'Santa Fe'],
      ['Santiago del Estero', 'Santiago del Estero'],
      ['Tierra del Fuego', 'Tierra del Fuego'],
      ['Tucumán', 'Tucumán'],
    ],
  },
  AS: {
    fmt: '%N%n%O%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'ACNOS',
    zip: '(96799)(?:[ \\-](\\d{4}))?',
    zipex: '96799',
    regionType: 'state',
    postalType: 'zip',
  },
  AT: {
    fmt: '%O%n%N%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '1010',
  },
  AU: {
    fmt: '%O%n%N%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'CS',
    zip: '\\d{4}',
    zipex: '2060',
    regionType: 'state',
    cityType: 'suburb',
    regions: [
      ['ACT', 'Australian Capital Territory'],
      ['JBT', 'Jervis Bay Territory'],
      ['NSW', 'New South Wales'],
      ['NT', 'Northern Territory'],
      ['QLD', 'Queensland'],
      ['SA', 'South Australia'],
      ['TAS', 'Tasmania'],
      ['VIC', 'Victoria'],
      ['WA', 'Western Australia'],
    ],
  },
  AW: {},
  AX: {
    fmt: '%O%n%N%n%A%nAX-%Z %C%nÅLAND',
    require: 'ACZ',
    zip: '22\\d{3}',
    zipex: '22150',
  },
  AZ: {
    fmt: '%N%n%O%n%A%nAZ %Z %C',
    zip: '\\d{4}',
    zipex: '1000',
  },
  BA: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '71000',
  },
  BB: {
    fmt: '%N%n%O%n%A%n%C, %S %Z',
    zip: 'BB\\d{5}',
    zipex: 'BB23026',
    regionType: 'parish',
    regions: [
      ['Christ Church', 'Christ Church'],
      ['Saint Andrew', 'Saint Andrew'],
      ['Saint George', 'Saint George'],
      ['Saint James', 'Saint James'],
      ['Saint John', 'Saint John'],
      ['Saint Joseph', 'Saint Joseph'],
      ['Saint Lucy', 'Saint Lucy'],
      ['Saint Michael', 'Saint Michael'],
      ['Saint Peter', 'Saint Peter'],
      ['Saint Philip', 'Saint Philip'],
      ['Saint Thomas', 'Saint Thomas'],
    ],
  },
  BD: {
    fmt: '%N%n%O%n%A%n%C - %Z',
    zip: '\\d{4}',
    zipex: '1340',
  },
  BE: {
    fmt: '%O%n%N%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '4000',
  },
  BF: {
    fmt: '%N%n%O%n%A%n%C %X',
  },
  BG: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '1000',
  },
  BH: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '(?:^|\\b)(?:1[0-2]|[1-9])\\d{2}(?:$|\\b)',
    zipex: '317',
  },
  BI: {},
  BJ: {
    upper: 'AC',
  },
  BL: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '9[78][01]\\d{2}',
    zipex: '97100',
  },
  BM: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '[A-Z]{2} ?[A-Z0-9]{2}',
    zipex: 'FL 07',
  },
  BN: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '[A-Z]{2} ?\\d{4}',
    zipex: 'BT2328',
  },
  BO: {
    upper: 'AC',
  },
  BQ: {},
  BR: {
    fmt: '%O%n%N%n%A%n%D%n%C-%S%n%Z',
    require: 'ASCZ',
    upper: 'CS',
    zip: '\\d{5}-?\\d{3}',
    zipex: '40301-110',
    regionType: 'state',
    regions: [
      ['AC', 'Acre'],
      ['AL', 'Alagoas'],
      ['AP', 'Amapá'],
      ['AM', 'Amazonas'],
      ['BA', 'Bahia'],
      ['CE', 'Ceará'],
      ['DF', 'Distrito Federal'],
      ['ES', 'Espírito Santo'],
      ['GO', 'Goiás'],
      ['MA', 'Maranhão'],
      ['MT', 'Mato Grosso'],
      ['MS', 'Mato Grosso do Sul'],
      ['MG', 'Minas Gerais'],
      ['PA', 'Pará'],
      ['PB', 'Paraíba'],
      ['PR', 'Paraná'],
      ['PE', 'Pernambuco'],
      ['PI', 'Piauí'],
      ['RJ', 'Rio de Janeiro'],
      ['RN', 'Rio Grande do Norte'],
      ['RS', 'Rio Grande do Sul'],
      ['RO', 'Rondônia'],
      ['RR', 'Roraima'],
      ['SC', 'Santa Catarina'],
      ['SP', 'São Paulo'],
      ['SE', 'Sergipe'],
      ['TO', 'Tocantins'],
    ],
  },
  BS: {
    fmt: '%N%n%O%n%A%n%C, %S',
    regionType: 'island',
    regions: [
      ['Abaco', 'Abaco Islands'],
      ['Acklins', 'Acklins'],
      ['Andros', 'Andros Island'],
      ['Berry Islands', 'Berry Islands'],
      ['Bimini', 'Bimini'],
      ['Cat Island', 'Cat Island'],
      ['Crooked Island', 'Crooked Island'],
      ['Eleuthera', 'Eleuthera'],
      ['Exuma', 'Exuma and Cays'],
      ['Grand Bahama', 'Grand Bahama'],
      ['Harbour Island', 'Harbour Island'],
      ['Inagua', 'Inagua'],
      ['Long Island', 'Long Island'],
      ['Mayaguana', 'Mayaguana'],
      ['N.P.', 'New Providence'],
      ['Ragged Island', 'Ragged Island'],
      ['Rum Cay', 'Rum Cay'],
      ['San Salvador', 'San Salvador'],
      ['Spanish Wells', 'Spanish Wells'],
    ],
  },
  BT: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{5}',
    zipex: '11001',
  },
  BW: {},
  BY: {
    fmt: '%O%n%N%n%A%n%Z, %C%n%S',
    zip: '\\d{6}',
    zipex: '223016',
    regions: [
      ['Брэсцкая вобласць', 'Bresckaja voblasć'],
      ['Віцебская вобласць', 'Viciebskaja voblasć'],
      ['Гомельская вобласць', 'Homieĺskaja voblasć'],
      ['горад Мінск', 'Horad Minsk'],
      ['Гродзенская вобласць', 'Hrodzienskaja voblasć'],
      ['Магілёўская вобласць', 'Mahilioŭskaja voblasć'],
      ['Мінская вобласць', 'Minskaja voblasć'],
    ],
  },
  BZ: {},
  CA: {
    fmt: '%N%n%O%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'ACNOSZ',
    zip: '[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z] ?\\d[ABCEGHJ-NPRSTV-Z]\\d',
    zipex: 'H3Z 2Y7',
    regions: [
      ['AB', 'Alberta'],
      ['BC', 'British Columbia'],
      ['MB', 'Manitoba'],
      ['NB', 'New Brunswick'],
      ['NL', 'Newfoundland and Labrador'],
      ['NT', 'Northwest Territories'],
      ['NS', 'Nova Scotia'],
      ['NU', 'Nunavut'],
      ['ON', 'Ontario'],
      ['PE', 'Prince Edward Island'],
      ['QC', 'Quebec'],
      ['SK', 'Saskatchewan'],
      ['YT', 'Yukon'],
    ],
  },
  CC: {
    fmt: '%O%n%N%n%A%n%C %S %Z',
    upper: 'CS',
    zip: '6799',
    zipex: '6799',
  },
  CD: {},
  CF: {},
  CG: {},
  CH: {
    fmt: '%O%n%N%n%A%nCH-%Z %C',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '2544',
  },
  CI: {
    fmt: '%N%n%O%n%X %A %C %X',
  },
  CK: {},
  CL: {
    fmt: '%N%n%O%n%A%n%Z %C%n%S',
    zip: '\\d{7}',
    zipex: '8340457',
    regions: [
      ['Antofagasta', 'Antofagasta'],
      ['Araucanía', 'Araucanía'],
      ['Arica y Parinacota', 'Arica y Parinacota'],
      ['Atacama', 'Atacama'],
      ['Aysén', 'Aysén del General Carlos Ibáñez del Campo'],
      ['Biobío', 'Biobío'],
      ['Coquimbo', 'Coquimbo'],
      ["O'Higgins", "Libertador General Bernardo O'Higgins"],
      ['Los Lagos', 'Los Lagos'],
      ['Los Ríos', 'Los Ríos'],
      ['Magallanes', 'Magallanes y de la Antártica Chilena'],
      ['Maule', 'Maule'],
      ['Región Metropolitana', 'Metropolitana de Santiago'],
      ['Ñuble', 'Ñuble'],
      ['Tarapacá', 'Tarapacá'],
      ['Valparaíso', 'Valparaíso'],
    ],
  },
  CM: {},
  CN: {
    fmt: '%Z%n%S%C%D%n%A%n%O%n%N',
    lfmt: '%N%n%O%n%A%n%D%n%C%n%S, %Z',
    require: 'ACSZ',
    upper: 'S',
    zip: '\\d{6}',
    zipex: '266033',
    regions: [
      ['安徽省', 'Anhui Sheng'],
      ['澳门', 'Macau'],
      ['北京市', 'Beijing Shi'],
      ['重庆市', 'Chongqing Shi'],
      ['福建省', 'Fujian Sheng'],
      ['甘肃省', 'Gansu Sheng'],
      ['广东省', 'Guangdong Sheng'],
      ['广西壮族自治区', 'Guangxi Zhuangzuzizhiqu'],
      ['贵州省', 'Guizhou Sheng'],
      ['海南省', 'Hainan Sheng'],
      ['河北省', 'Hebei Sheng'],
      ['河南省', 'Henan Sheng'],
      ['黑龙江省', 'Heilongjiang Sheng'],
      ['湖北省', 'Hubei Sheng'],
      ['湖南省', 'Hunan Sheng'],
      ['吉林省', 'Jilin Sheng'],
      ['江苏省', 'Jiangsu Sheng'],
      ['江西省', 'Jiangxi Sheng'],
      ['辽宁省', 'Liaoning Sheng'],
      ['内蒙古自治区', 'Neimenggu Zizhiqu'],
      ['宁夏回族自治区', 'Ningxia Huizuzizhiqu'],
      ['青海省', 'Qinghai Sheng'],
      ['山东省', 'Shandong Sheng'],
      ['山西省', 'Shanxi Sheng'],
      ['陕西省', 'Shaanxi Sheng'],
      ['上海市', 'Shanghai Shi'],
      ['四川省', 'Sichuan Sheng'],
      ['台湾', 'Taiwan'],
      ['天津市', 'Tianjin Shi'],
      ['西藏自治区', 'Xizang Zizhiqu'],
      ['香港', 'Hong Kong'],
      ['新疆维吾尔自治区', 'Xinjiang Weiwuerzizhiqu'],
      ['云南省', 'Yunnan Sheng'],
      ['浙江省', 'Zhejiang Sheng'],
    ],
  },
  CO: {
    fmt: '%N%n%O%n%A%n%D%n%C, %S, %Z',
    require: 'AS',
    zip: '\\d{6}',
    zipex: '111221',
    regionType: 'department',
    regions: [
      ['Amazonas', 'Amazonas'],
      ['Antioquia', 'Antioquia'],
      ['Arauca', 'Arauca'],
      ['Atlántico', 'Atlántico'],
      ['Bogotá', 'Bogotá'],
      ['Bolívar', 'Bolívar'],
      ['Boyacá', 'Boyacá'],
      ['Caldas', 'Caldas'],
      ['Caquetá', 'Caquetá'],
      ['Casanare', 'Casanare'],
      ['Cauca', 'Cauca'],
      ['Cesar', 'Cesar'],
      ['Chocó', 'Chocó'],
      ['Córdoba', 'Córdoba'],
      ['Cundinamarca', 'Cundinamarca'],
      ['Guainía', 'Guainía'],
      ['Guaviare', 'Guaviare'],
      ['Huila', 'Huila'],
      ['La Guajira', 'La Guajira'],
      ['Magdalena', 'Magdalena'],
      ['Meta', 'Meta'],
      ['Nariño', 'Nariño'],
      ['Norte de Santander', 'Norte de Santander'],
      ['Putumayo', 'Putumayo'],
      ['Quindío', 'Quindío'],
      ['Risaralda', 'Risaralda'],
      ['San Andrés y Providencia', 'San Andrés y Providencia'],
      ['Santander', 'Santander'],
      ['Sucre', 'Sucre'],
      ['Tolima', 'Tolima'],
      ['Valle del Cauca', 'Valle del Cauca'],
      ['Vaupés', 'Vaupés'],
      ['Vichada', 'Vichada'],
    ],
  },
  CR: {
    fmt: '%N%n%O%n%A%n%S, %C%n%Z',
    require: 'ACS',
    zip: '\\d{4,5}|\\d{3}-\\d{4}',
    zipex: '1000',
    regions: [
      ['Alajuela', 'Alajuela'],
      ['Cartago', 'Cartago'],
      ['Guanacaste', 'Guanacaste'],
      ['Heredia', 'Heredia'],
      ['Limón', 'Limón'],
      ['Puntarenas', 'Puntarenas'],
      ['San José', 'San José'],
    ],
  },
  CU: {
    fmt: '%N%n%O%n%A%n%C %S%n%Z',
    zip: '\\d{5}',
    zipex: '10700',
    regions: [
      ['Artemisa', 'Artemisa'],
      ['Camagüey', 'Camagüey'],
      ['Ciego de Ávila', 'Ciego de Ávila'],
      ['Cienfuegos', 'Cienfuegos'],
      ['Granma', 'Granma'],
      ['Guantánamo', 'Guantánamo'],
      ['Holguín', 'Holguín'],
      ['Isla de la Juventud', 'Isla de la Juventud'],
      ['La Habana', 'La Habana'],
      ['Las Tunas', 'Las Tunas'],
      ['Matanzas', 'Matanzas'],
      ['Mayabeque', 'Mayabeque'],
      ['Pinar del Río', 'Pinar del Río'],
      ['Sancti Spíritus', 'Sancti Spíritus'],
      ['Santiago de Cuba', 'Santiago de Cuba'],
      ['Villa Clara', 'Villa Clara'],
    ],
  },
  CV: {
    fmt: '%N%n%O%n%A%n%Z %C%n%S',
    zip: '\\d{4}',
    zipex: '7600',
    regionType: 'island',
    regions: [
      ['Boa Vista', 'Boa Vista'],
      ['Brava', 'Brava'],
      ['Fogo', 'Fogo'],
      ['Maio', 'Maio'],
      ['Sal', 'Sal'],
      ['Santiago', 'Santiago'],
      ['Santo Antão', 'Santo Antão'],
      ['São Nicolau', 'São Nicolau'],
      ['São Vicente', 'São Vicente'],
    ],
  },
  CW: {},
  CX: {
    fmt: '%O%n%N%n%A%n%C %S %Z',
    upper: 'CS',
    zip: '6798',
    zipex: '6798',
  },
  CY: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '2008',
  },
  CZ: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{3} ?\\d{2}',
    zipex: '100 00',
  },
  DE: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{5}',
    zipex: '26133',
  },
  DJ: {},
  DK: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '8660',
  },
  DM: {},
  DO: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '11903',
  },
  DZ: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '40304',
  },
  EC: {
    fmt: '%N%n%O%n%A%n%Z%n%C',
    upper: 'CZ',
    zip: '\\d{6}',
    zipex: '090105',
  },
  EE: {
    fmt: '%N%n%O%n%A%n%Z %C %S',
    require: 'ACZ',
    zip: '\\d{5}',
    zipex: '69501',
    regions: [
      ['Harjumaa', 'Harjumaa'],
      ['Hiiumaa', 'Hiiumaa'],
      ['Ida-Virumaa', 'Ida-Virumaa'],
      ['Jõgevamaa', 'Jõgevamaa'],
      ['Järvamaa', 'Järvamaa'],
      ['Lääne-Virumaa', 'Lääne-Virumaa'],
      ['Läänemaa', 'Läänemaa'],
      ['Põlvamaa', 'Põlvamaa'],
      ['Pärnumaa', 'Pärnumaa'],
      ['Raplamaa', 'Raplamaa'],
      ['Saaremaa', 'Saaremaa'],
      ['Tartumaa', 'Tartumaa'],
      ['Valgamaa', 'Valgamaa'],
      ['Viljandimaa', 'Viljandimaa'],
      ['Võrumaa', 'Võrumaa'],
    ],
  },
  EG: {
    fmt: '%N%n%O%n%A%n%C%n%S%n%Z',
    lfmt: '%N%n%O%n%A%n%C%n%S%n%Z',
    zip: '\\d{7}|\\d{5}',
    zipex: '4460232',
    regions: [
      ['أسوان', 'Aswan Governorate'],
      ['أسيوط', 'Asyut Governorate'],
      ['الإسكندرية', 'Alexandria Governorate'],
      ['الإسماعيلية', 'Ismailia Governorate'],
      ['الأقصر', 'Luxor Governorate'],
      ['البحر الأحمر', 'Red Sea Governorate'],
      ['البحيرة', 'El Beheira Governorate'],
      ['الجيزة', 'Giza Governorate'],
      ['الدقهلية', 'Dakahlia Governorate'],
      ['السويس', 'Suez Governorate'],
      ['الشرقية', 'Ash Sharqia Governorate'],
      ['الغربية', 'Gharbia Governorate'],
      ['الفيوم', 'Faiyum Governorate'],
      ['القاهرة', 'Cairo Governorate'],
      ['القليوبية', 'Qalyubia Governorate'],
      ['المنوفية', 'Menofia Governorate'],
      ['المنيا', 'Menia Governorate'],
      ['الوادي الجديد', 'New Valley Governorate'],
      ['بني سويف', 'Beni Suef Governorate'],
      ['بورسعيد', 'Port Said Governorate'],
      ['جنوب سيناء', 'South Sinai Governorate'],
      ['دمياط', 'Damietta Governorate'],
      ['سوهاج', 'Sohag Governorate'],
      ['شمال سيناء', 'North Sinai Governorate'],
      ['قنا', 'Qena Governorate'],
      ['كفر الشيخ', 'Kafr El Sheikh Governorate'],
      ['مطروح', 'Matrouh Governorate'],
    ],
  },
  EH: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '70000',
  },
  ER: {},
  ES: {
    fmt: '%N%n%O%n%A%n%Z %C %S',
    require: 'ACSZ',
    upper: 'CS',
    zip: '\\d{5}',
    zipex: '28039',
    regions: [
      ['VI', 'Álava'],
      ['AB', 'Albacete'],
      ['A', 'Alicante'],
      ['AL', 'Almería'],
      ['O', 'Asturias'],
      ['AV', 'Ávila'],
      ['BA', 'Badajoz'],
      ['B', 'Barcelona'],
      ['BU', 'Burgos'],
      ['CC', 'Cáceres'],
      ['CA', 'Cádiz'],
      ['S', 'Cantabria'],
      ['CS', 'Castellón'],
      ['CE', 'Ceuta'],
      ['CR', 'Ciudad Real'],
      ['CO', 'Córdoba'],
      ['CU', 'Cuenca'],
      ['GI', 'Girona'],
      ['GR', 'Granada'],
      ['GU', 'Guadalajara'],
      ['SS', 'Guipúzcoa'],
      ['H', 'Huelva'],
      ['HU', 'Huesca'],
      ['PM', 'Islas Baleares'],
      ['J', 'Jaén'],
      ['C', 'La Coruña'],
      ['LO', 'La Rioja'],
      ['GC', 'Las Palmas'],
      ['LE', 'León'],
      ['L', 'Lérida'],
      ['LU', 'Lugo'],
      ['M', 'Madrid'],
      ['MA', 'Málaga'],
      ['ML', 'Melilla'],
      ['MU', 'Murcia'],
      ['NA', 'Navarra'],
      ['OR', 'Ourense'],
      ['P', 'Palencia'],
      ['PO', 'Pontevedra'],
      ['SA', 'Salamanca'],
      ['TF', 'Santa Cruz de Tenerife'],
      ['SG', 'Segovia'],
      ['SE', 'Sevilla'],
      ['SO', 'Soria'],
      ['T', 'Tarragona'],
      ['TE', 'Teruel'],
      ['TO', 'Toledo'],
      ['V', 'Valencia'],
      ['VA', 'Valladolid'],
      ['BI', 'Vizcaya'],
      ['ZA', 'Zamora'],
      ['Z', 'Zaragoza'],
    ],
  },
  ET: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '1000',
  },
  FI: {
    fmt: '%O%n%N%n%A%nFI-%Z %C',
    require: 'ACZ',
    zip: '\\d{5}',
    zipex: '00550',
  },
  FJ: {},
  FK: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: 'FIQQ 1ZZ',
    zipex: 'FIQQ 1ZZ',
  },
  FM: {
    fmt: '%N%n%O%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'ACNOS',
    zip: '(9694[1-4])(?:[ \\-](\\d{4}))?',
    zipex: '96941',
    regionType: 'state',
    postalType: 'zip',
    regions: [
      ['Chuuk', 'Chuuk'],
      ['Kosrae', 'Kosrae'],
      ['Pohnpei', 'Pohnpei'],
      ['Yap', 'Yap'],
    ],
  },
  FO: {
    fmt: '%N%n%O%n%A%nFO%Z %C',
    zip: '\\d{3}',
    zipex: '100',
  },
  FR: {
    fmt: '%O%n%N%n%A%n%Z %C',
    require: 'ACZ',
    upper: 'CX',
    zip: '\\d{2} ?\\d{3}',
    zipex: '33380',
  },
  GA: {},
  GB: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: 'GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BF|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}',
    zipex: 'EC1Y 8SY',
    cityType: 'post_town',
  },
  GD: {},
  GE: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '0101',
  },
  GF: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '9[78]3\\d{2}',
    zipex: '97300',
  },
  GG: {
    fmt: '%N%n%O%n%A%n%C%nGUERNSEY%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: 'GY\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    zipex: 'GY1 1AA',
  },
  GH: {},
  GI: {
    fmt: '%N%n%O%n%A%nGIBRALTAR%n%Z',
    require: 'A',
    zip: 'GX11 1AA',
    zipex: 'GX11 1AA',
  },
  GL: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '39\\d{2}',
    zipex: '3900',
  },
  GM: {},
  GN: {
    fmt: '%N%n%O%n%Z %A %C',
    zip: '\\d{3}',
    zipex: '001',
  },
  GP: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '9[78][01]\\d{2}',
    zipex: '97100',
  },
  GQ: {},
  GR: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{3} ?\\d{2}',
    zipex: '151 24',
  },
  GT: {
    fmt: '%N%n%O%n%A%n%Z- %C',
    zip: '\\d{5}',
    zipex: '09001',
  },
  GU: {
    fmt: '%N%n%O%n%A%n%C %Z',
    require: 'ACZ',
    upper: 'ACNO',
    zip: '(969(?:[12]\\d|3[12]))(?:[ \\-](\\d{4}))?',
    zipex: '96910',
    postalType: 'zip',
  },
  GW: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '1000',
  },
  GY: {},
  HK: {
    fmt: '%S%n%C%n%A%n%O%n%N',
    lfmt: '%N%n%O%n%A%n%C%n%S',
    require: 'AS',
    upper: 'S',
    regionType: 'area',
    cityType: 'district',
    regions: [
      ['Kowloon', '九龍'],
      ['Hong Kong Island', '香港島'],
      ['New Territories', '新界'],
    ],
  },
  HN: {
    fmt: '%N%n%O%n%A%n%C, %S%n%Z',
    require: 'ACS',
    zip: '\\d{5}',
    zipex: '31301',
    regionType: 'department',
    regions: [
      ['Atlántida', 'Atlántida'],
      ['Choluteca', 'Choluteca'],
      ['Colón', 'Colón'],
      ['Comayagua', 'Comayagua'],
      ['Copán', 'Copán'],
      ['Cortés', 'Cortés'],
      ['El Paraíso', 'El Paraíso'],
      ['Francisco Morazán', 'Francisco Morazán'],
      ['Gracias a Dios', 'Gracias a Dios'],
      ['Intibucá', 'Intibucá'],
      ['Islas de la Bahía', 'Islas de la Bahía'],
      ['La Paz', 'La Paz'],
      ['Lempira', 'Lempira'],
      ['Ocotepeque', 'Ocotepeque'],
      ['Olancho', 'Olancho'],
      ['Santa Bárbara', 'Santa Bárbara'],
      ['Valle', 'Valle'],
      ['Yoro', 'Yoro'],
    ],
  },
  HR: {
    fmt: '%N%n%O%n%A%nHR-%Z %C',
    zip: '\\d{5}',
    zipex: '10000',
  },
  HT: {
    fmt: '%N%n%O%n%A%nHT%Z %C',
    zip: '\\d{4}',
    zipex: '6120',
  },
  HU: {
    fmt: '%N%n%O%n%C%n%A%n%Z',
    require: 'ACZ',
    upper: 'ACNO',
    zip: '\\d{4}',
    zipex: '1037',
  },
  ID: {
    fmt: '%N%n%O%n%A%n%C%n%S %Z',
    require: 'AS',
    zip: '\\d{5}',
    zipex: '40115',
    regions: [
      ['Aceh', 'Aceh'],
      ['Bali', 'Bali'],
      ['Banten', 'Banten'],
      ['Bengkulu', 'Bengkulu'],
      ['Daerah Istimewa Yogyakarta', 'Special Region of Yogyakarta'],
      ['DKI Jakarta', 'Jakarta'],
      ['Gorontalo', 'Gorontalo'],
      ['Jambi', 'Jambi'],
      ['Jawa Barat', 'West Java'],
      ['Jawa Tengah', 'Central Java'],
      ['Jawa Timur', 'East Java'],
      ['Kalimantan Barat', 'West Kalimantan'],
      ['Kalimantan Selatan', 'South Kalimantan'],
      ['Kalimantan Tengah', 'Central Kalimantan'],
      ['Kalimantan Timur', 'East Kalimantan'],
      ['Kalimantan Utara', 'North Kalimantan'],
      ['Kepulauan Bangka Belitung', 'Bangka Belitung Islands'],
      ['Kepulauan Riau', 'Riau Islands'],
      ['Lampung', 'Lampung'],
      ['Maluku', 'Maluku'],
      ['Maluku Utara', 'North Maluku'],
      ['Nusa Tenggara Barat', 'West Nusa Tenggara'],
      ['Nusa Tenggara Timur', 'East Nusa Tenggara'],
      ['Papua', 'Papua'],
      ['Papua Barat', 'West Papua'],
      ['Riau', 'Riau'],
      ['Sulawesi Barat', 'West Sulawesi'],
      ['Sulawesi Selatan', 'South Sulawesi'],
      ['Sulawesi Tengah', 'Central Sulawesi'],
      ['Sulawesi Tenggara', 'South East Sulawesi'],
      ['Sulawesi Utara', 'North Sulawesi'],
      ['Sumatera Barat', 'West Sumatra'],
      ['Sumatera Selatan', 'South Sumatra'],
      ['Sumatera Utara', 'North Sumatra'],
    ],
  },
  IE: {
    fmt: '%N%n%O%n%A%n%D%n%C%n%S%n%Z',
    zip: '[\\dA-Z]{3} ?[\\dA-Z]{4}',
    zipex: 'A65 F4E2',
    regionType: 'county',
    postalType: 'eircode',
    regions: [
      ['Co. Carlow', 'Co. Carlow'],
      ['Co. Cavan', 'Co. Cavan'],
      ['Co. Clare', 'Co. Clare'],
      ['Co. Cork', 'Co. Cork'],
      ['Co. Donegal', 'Co. Donegal'],
      ['Co. Dublin', 'Co. Dublin'],
      ['Co. Galway', 'Co. Galway'],
      ['Co. Kerry', 'Co. Kerry'],
      ['Co. Kildare', 'Co. Kildare'],
      ['Co. Kilkenny', 'Co. Kilkenny'],
      ['Co. Laois', 'Co. Laois'],
      ['Co. Leitrim', 'Co. Leitrim'],
      ['Co. Limerick', 'Co. Limerick'],
      ['Co. Longford', 'Co. Longford'],
      ['Co. Louth', 'Co. Louth'],
      ['Co. Mayo', 'Co. Mayo'],
      ['Co. Meath', 'Co. Meath'],
      ['Co. Monaghan', 'Co. Monaghan'],
      ['Co. Offaly', 'Co. Offaly'],
      ['Co. Roscommon', 'Co. Roscommon'],
      ['Co. Sligo', 'Co. Sligo'],
      ['Co. Tipperary', 'Co. Tipperary'],
      ['Co. Waterford', 'Co. Waterford'],
      ['Co. Westmeath', 'Co. Westmeath'],
      ['Co. Wexford', 'Co. Wexford'],
      ['Co. Wicklow', 'Co. Wicklow'],
    ],
  },
  IL: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{5}(?:\\d{2})?',
    zipex: '9614303',
  },
  IM: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: 'IM\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    zipex: 'IM2 1AA',
  },
  IN: {
    fmt: '%N%n%O%n%A%n%T%n%F%n%L%n%C %Z%n%S',
    require: 'ACSZ',
    zip: '\\d{6}',
    zipex: '110034',
    regionType: 'state',
    postalType: 'pin',
    regions: [
      ['Andaman and Nicobar Islands', 'Andaman & Nicobar'],
      ['Andhra Pradesh', 'Andhra Pradesh'],
      ['Arunachal Pradesh', 'Arunachal Pradesh'],
      ['Assam', 'Assam'],
      ['Bihar', 'Bihar'],
      ['Chandigarh', 'Chandigarh'],
      ['Chhattisgarh', 'Chhattisgarh'],
      ['Dadra and Nagar Haveli and Daman and Diu', 'Dadra & Nagar Haveli & Daman & Diu'],
      ['Delhi', 'Delhi'],
      ['Goa', 'Goa'],
      ['Gujarat', 'Gujarat'],
      ['Haryana', 'Haryana'],
      ['Himachal Pradesh', 'Himachal Pradesh'],
      ['Jammu and Kashmir', 'Jammu & Kashmir'],
      ['Jharkhand', 'Jharkhand'],
      ['Karnataka', 'Karnataka'],
      ['Kerala', 'Kerala'],
      ['Ladakh', 'Ladakh'],
      ['Lakshadweep', 'Lakshadweep'],
      ['Madhya Pradesh', 'Madhya Pradesh'],
      ['Maharashtra', 'Maharashtra'],
      ['Manipur', 'Manipur'],
      ['Meghalaya', 'Meghalaya'],
      ['Mizoram', 'Mizoram'],
      ['Nagaland', 'Nagaland'],
      ['Odisha', 'Odisha'],
      ['Puducherry', 'Puducherry'],
      ['Punjab', 'Punjab'],
      ['Rajasthan', 'Rajasthan'],
      ['Sikkim', 'Sikkim'],
      ['Tamil Nadu', 'Tamil Nadu'],
      ['Telangana', 'Telangana'],
      ['Tripura', 'Tripura'],
      ['Uttar Pradesh', 'Uttar Pradesh'],
      ['Uttarakhand', 'Uttarakhand'],
      ['West Bengal', 'West Bengal'],
    ],
  },
  IO: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: 'BBND 1ZZ',
    zipex: 'BBND 1ZZ',
  },
  IQ: {
    fmt: '%O%n%N%n%A%n%C, %S%n%Z',
    require: 'ACS',
    upper: 'CS',
    zip: '\\d{5}',
    zipex: '31001',
    regions: [
      ['أربيل', 'Erbil'],
      ['إقليم كوردستان', 'Kurdistan Region'],
      ['الانبار', 'Al Anbar'],
      ['البصرة', 'Basra'],
      ['السليمانية', 'Sulaymaniyah'],
      ['القادسية', 'Al-Qādisiyyah'],
      ['المثنى', 'Al Muthanna'],
      ['النجف', 'Najaf'],
      ['بابل', 'Babylon'],
      ['بغداد', 'Baghdad'],
      ['دهوك', 'Duhok'],
      ['ديالى', 'Diyala'],
      ['ذي قار', 'Dhi Qar'],
      ['صلاح الدين', 'Saladin'],
      ['كربلاء', 'Karbala'],
      ['كركوك', 'Kirkuk'],
      ['ميسان', 'Maysan'],
      ['نينوى', 'Nineveh'],
      ['واسط', 'Wasit'],
    ],
  },
  IR: {
    fmt: '%O%n%N%n%S%n%C, %D%n%A%n%Z',
    zip: '\\d{5}-?\\d{5}',
    zipex: '11936-12345',
    regions: [
      ['استان آذربایجان شرقی', 'East Azerbaijan Province'],
      ['استان آذربایجان غربی', 'West Azerbaijan Province'],
      ['استان اردبیل', 'Ardabil Province'],
      ['استان اصفهان', 'Isfahan Province'],
      ['استان البرز', 'Alborz Province'],
      ['استان ایلام', 'Ilam Province'],
      ['استان بوشهر', 'Bushehr Province'],
      ['استان تهران', 'Tehran Province'],
      ['استان چهارمحال و بختیاری', 'Chaharmahal and Bakhtiari Province'],
      ['استان خراسان جنوبی', 'South Khorasan Province'],
      ['استان خراسان رضوی', 'Razavi Khorasan Province'],
      ['استان خراسان شمالی', 'North Khorasan Province'],
      ['استان خوزستان', 'Khuzestan Province'],
      ['استان زنجان', 'Zanjan Province'],
      ['استان سمنان', 'Semnan Province'],
      ['استان سیستان و بلوچستان', 'Sistan and Baluchestan Province'],
      ['استان فارس', 'Fars Province'],
      ['استان قزوین', 'Qazvin Province'],
      ['استان قم', 'Qom Province'],
      ['استان کردستان', 'Kurdistan Province'],
      ['استان کرمان', 'Kerman Province'],
      ['استان کرمانشاه', 'Kermanshah Province'],
      ['استان کهگیلویه و بویراحمد', 'Kohgiluyeh and Boyer-Ahmad Province'],
      ['استان گلستان', 'Golestan Province'],
      ['استان گیلان', 'Gilan Province'],
      ['استان لرستان', 'Lorestan Province'],
      ['استان مازندران', 'Mazandaran Province'],
      ['استان مرکزی', 'Markazi Province'],
      ['استان هرمزگان', 'Hormozgan Province'],
      ['استان همدان', 'Hamadan Province'],
      ['استان یزد', 'Yazd Province'],
    ],
  },
  IS: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{3}',
    zipex: '320',
  },
  IT: {
    fmt: '%N%n%O%n%A%n%Z %C %S',
    require: 'ACSZ',
    upper: 'CS',
    zip: '\\d{5}',
    zipex: '00144',
    regions: [
      ['AG', 'Agrigento'],
      ['AL', 'Alessandria'],
      ['AN', 'Ancona'],
      ['AO', 'Aosta'],
      ['AR', 'Arezzo'],
      ['AP', 'Ascoli Piceno'],
      ['AT', 'Asti'],
      ['AV', 'Avellino'],
      ['BA', 'Bari'],
      ['BT', 'Barletta-Andria-Trani'],
      ['BL', 'Belluno'],
      ['BN', 'Benevento'],
      ['BG', 'Bergamo'],
      ['BI', 'Biella'],
      ['BO', 'Bologna'],
      ['BZ', 'Bolzano'],
      ['BS', 'Brescia'],
      ['BR', 'Brindisi'],
      ['CA', 'Cagliari'],
      ['CL', 'Caltanissetta'],
      ['CB', 'Campobasso'],
      ['CE', 'Caserta'],
      ['CT', 'Catania'],
      ['CZ', 'Catanzaro'],
      ['CH', 'Chieti'],
      ['CO', 'Como'],
      ['CS', 'Cosenza'],
      ['CR', 'Cremona'],
      ['KR', 'Crotone'],
      ['CN', 'Cuneo'],
      ['EN', 'Enna'],
      ['FM', 'Fermo'],
      ['FE', 'Ferrara'],
      ['FI', 'Firenze'],
      ['FG', 'Foggia'],
      ['FC', 'Forlì-Cesena'],
      ['FR', 'Frosinone'],
      ['GA', 'Gallura Nord-Est Sardegna'],
      ['GE', 'Genova'],
      ['GO', 'Gorizia'],
      ['GR', 'Grosseto'],
      ['IM', 'Imperia'],
      ['IS', 'Isernia'],
      ['AQ', "L'Aquila"],
      ['SP', 'La Spezia'],
      ['LT', 'Latina'],
      ['LE', 'Lecce'],
      ['LC', 'Lecco'],
      ['LI', 'Livorno'],
      ['LO', 'Lodi'],
      ['LU', 'Lucca'],
      ['MC', 'Macerata'],
      ['MN', 'Mantova'],
      ['MS', 'Massa-Carrara'],
      ['MT', 'Matera'],
      ['VS', 'Medio Campidano'],
      ['ME', 'Messina'],
      ['MI', 'Milano'],
      ['MO', 'Modena'],
      ['MB', 'Monza e Brianza'],
      ['NA', 'Napoli'],
      ['NO', 'Novara'],
      ['NU', 'Nuoro'],
      ['OG', 'Ogliastra'],
      ['OR', 'Oristano'],
      ['PD', 'Padova'],
      ['PA', 'Palermo'],
      ['PR', 'Parma'],
      ['PV', 'Pavia'],
      ['PG', 'Perugia'],
      ['PU', 'Pesaro e Urbino'],
      ['PE', 'Pescara'],
      ['PC', 'Piacenza'],
      ['PI', 'Pisa'],
      ['PT', 'Pistoia'],
      ['PN', 'Pordenone'],
      ['PZ', 'Potenza'],
      ['PO', 'Prato'],
      ['RG', 'Ragusa'],
      ['RA', 'Ravenna'],
      ['RC', 'Reggio Calabria'],
      ['RE', 'Reggio Emilia'],
      ['RI', 'Rieti'],
      ['RN', 'Rimini'],
      ['RM', 'Roma'],
      ['RO', 'Rovigo'],
      ['SA', 'Salerno'],
      ['SS', 'Sassari'],
      ['SV', 'Savona'],
      ['SI', 'Siena'],
      ['SR', 'Siracusa'],
      ['SO', 'Sondrio'],
      ['SU', 'Sud Sardegna'],
      ['SD', 'Sulcis Iglesiente'],
      ['TA', 'Taranto'],
      ['TE', 'Teramo'],
      ['TR', 'Terni'],
      ['TO', 'Torino'],
      ['TP', 'Trapani'],
      ['TN', 'Trento'],
      ['TV', 'Treviso'],
      ['TS', 'Trieste'],
      ['UD', 'Udine'],
      ['VA', 'Varese'],
      ['VE', 'Venezia'],
      ['VB', 'Verbano-Cusio-Ossola'],
      ['VC', 'Vercelli'],
      ['VR', 'Verona'],
      ['VV', 'Vibo Valentia'],
      ['VI', 'Vicenza'],
      ['VT', 'Viterbo'],
    ],
  },
  JE: {
    fmt: '%N%n%O%n%A%n%C%nJERSEY%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: 'JE\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    zipex: 'JE1 1AA',
  },
  JM: {
    fmt: '%N%n%O%n%A%n%C%n%S %X',
    require: 'ACS',
    regionType: 'parish',
    regions: [
      ['Clarendon', 'Clarendon'],
      ['Hanover', 'Hanover'],
      ['Kingston', 'Kingston'],
      ['Manchester', 'Manchester'],
      ['Portland', 'Portland'],
      ['St. Andrew', 'St. Andrew'],
      ['St. Ann', 'St. Ann'],
      ['St. Catherine', 'St. Catherine'],
      ['St. Elizabeth', 'St. Elizabeth'],
      ['St. James', 'St. James'],
      ['St. Mary', 'St. Mary'],
      ['St. Thomas', 'St. Thomas'],
      ['Trelawny', 'Trelawny'],
      ['Westmoreland', 'Westmoreland'],
    ],
  },
  JO: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{5}',
    zipex: '11937',
  },
  JP: {
    fmt: '〒%Z%n%S%n%A%n%O%n%N',
    lfmt: '%N%n%O%n%A, %S%n%Z',
    require: 'ASZ',
    upper: 'S',
    zip: '\\d{3}-?\\d{4}',
    zipex: '154-0023',
    regionType: 'prefecture',
    regions: [
      ['北海道', 'Hokkaido'],
      ['青森県', 'Aomori'],
      ['岩手県', 'Iwate'],
      ['宮城県', 'Miyagi'],
      ['秋田県', 'Akita'],
      ['山形県', 'Yamagata'],
      ['福島県', 'Fukushima'],
      ['茨城県', 'Ibaraki'],
      ['栃木県', 'Tochigi'],
      ['群馬県', 'Gunma'],
      ['埼玉県', 'Saitama'],
      ['千葉県', 'Chiba'],
      ['東京都', 'Tokyo'],
      ['神奈川県', 'Kanagawa'],
      ['新潟県', 'Niigata'],
      ['富山県', 'Toyama'],
      ['石川県', 'Ishikawa'],
      ['福井県', 'Fukui'],
      ['山梨県', 'Yamanashi'],
      ['長野県', 'Nagano'],
      ['岐阜県', 'Gifu'],
      ['静岡県', 'Shizuoka'],
      ['愛知県', 'Aichi'],
      ['三重県', 'Mie'],
      ['滋賀県', 'Shiga'],
      ['京都府', 'Kyoto'],
      ['大阪府', 'Osaka'],
      ['兵庫県', 'Hyogo'],
      ['奈良県', 'Nara'],
      ['和歌山県', 'Wakayama'],
      ['鳥取県', 'Tottori'],
      ['島根県', 'Shimane'],
      ['岡山県', 'Okayama'],
      ['広島県', 'Hiroshima'],
      ['山口県', 'Yamaguchi'],
      ['徳島県', 'Tokushima'],
      ['香川県', 'Kagawa'],
      ['愛媛県', 'Ehime'],
      ['高知県', 'Kochi'],
      ['福岡県', 'Fukuoka'],
      ['佐賀県', 'Saga'],
      ['長崎県', 'Nagasaki'],
      ['熊本県', 'Kumamoto'],
      ['大分県', 'Oita'],
      ['宮崎県', 'Miyazaki'],
      ['鹿児島県', 'Kagoshima'],
      ['沖縄県', 'Okinawa'],
    ],
  },
  KE: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: '\\d{5}',
    zipex: '20100',
  },
  KG: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{6}',
    zipex: '720001',
  },
  KH: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{5,6}',
    zipex: '120101',
  },
  KI: {
    fmt: '%N%n%O%n%A%n%S%n%C',
    upper: 'ACNOS',
    regionType: 'island',
  },
  KM: {
    upper: 'AC',
  },
  KN: {
    fmt: '%N%n%O%n%A%n%C, %S',
    require: 'ACS',
    regionType: 'island',
    regions: [
      ['Nevis', 'Nevis'],
      ['St. Kitts', 'St. Kitts'],
    ],
  },
  KR: {
    fmt: '%S %C%D%n%A%n%O%n%N%n%Z',
    lfmt: '%N%n%O%n%A%n%D%n%C%n%S%n%Z',
    require: 'ACSZ',
    upper: 'Z',
    zip: '\\d{5}',
    zipex: '03051',
    regionType: 'do_si',
    regions: [
      ['강원도', 'Gangwon-do'],
      ['경기도', 'Gyeonggi-do'],
      ['경상남도', 'Gyeongsangnam-do'],
      ['경상북도', 'Gyeongsangbuk-do'],
      ['광주광역시', 'Gwangju'],
      ['대구광역시', 'Daegu'],
      ['대전광역시', 'Daejeon'],
      ['부산광역시', 'Busan'],
      ['서울특별시', 'Seoul'],
      ['세종특별자치시', 'Sejong'],
      ['울산광역시', 'Ulsan'],
      ['인천광역시', 'Incheon'],
      ['전라남도', 'Jeollanam-do'],
      ['전라북도', 'Jeollabuk-do'],
      ['제주특별자치도', 'Jeju-do'],
      ['충청남도', 'Chungcheongnam-do'],
      ['충청북도', 'Chungcheongbuk-do'],
    ],
  },
  KW: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '54541',
  },
  KY: {
    fmt: '%N%n%O%n%A%n%S %Z',
    require: 'AS',
    zip: 'KY\\d-\\d{4}',
    zipex: 'KY1-1100',
    regionType: 'island',
    regions: [
      ['Cayman Brac', 'Cayman Brac'],
      ['Grand Cayman', 'Grand Cayman'],
      ['Little Cayman', 'Little Cayman'],
    ],
  },
  KZ: {
    fmt: '%Z%n%S%n%C%n%A%n%O%n%N',
    zip: '\\d{6}',
    zipex: '040900',
    regions: [
      ['Абай облысы', 'Abai Region'],
      ['Ақмола облысы', 'Akmola Region'],
      ['Ақтөбе облысы', 'Aktobe Region'],
      ['Алматы', 'Almaty'],
      ['Алматы облысы', 'Almaty Region'],
      ['Астана', 'Astana'],
      ['Атырау облысы', 'Atyrau Region'],
      ['Батыс Қазақстан облысы', 'West Kazakhstan Region'],
      ['Жамбыл облысы', 'Jambyl Region'],
      ['Жетісу облысы', 'Jetisu Region'],
      ['Қарағанды облысы', 'Karaganda Region'],
      ['Қостанай облысы', 'Kostanay Region'],
      ['Қызылорда облысы', 'Kyzylorda Region'],
      ['Маңғыстау облысы', 'Mangystau Region'],
      ['Павлодар облысы', 'Pavlodar Region'],
      ['Солтүстік Қазақстан облысы', 'North Kazakhstan Region'],
      ['Түркістан облысы', 'Turkistan Region'],
      ['Ұлытау облысы', 'Ulytau Region'],
      ['Шығыс Қазақстан облысы', 'East Kazakhstan Region'],
      ['Шымкент', 'Shymkent'],
    ],
  },
  LA: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '01160',
  },
  LB: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '(?:\\d{4})(?: ?(?:\\d{4}))?',
    zipex: '2038 3054',
  },
  LC: {},
  LI: {
    fmt: '%O%n%N%n%A%nFL-%Z %C',
    require: 'ACZ',
    zip: '948[5-9]|949[0-8]',
    zipex: '9496',
  },
  LK: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: '\\d{5}',
    zipex: '20000',
  },
  LR: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '1000',
  },
  LS: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{3}',
    zipex: '100',
  },
  LT: {
    fmt: '%O%n%N%n%A%nLT-%Z %C %S',
    require: 'ACZ',
    zip: '\\d{5}',
    zipex: '04340',
  },
  LU: {
    fmt: '%O%n%N%n%A%nL-%Z %C',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '4750',
  },
  LV: {
    fmt: '%N%n%O%n%A%n%S%n%C, %Z',
    require: 'ACZ',
    zip: 'LV-\\d{4}',
    zipex: 'LV-1073',
  },
  LY: {},
  MA: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '53000',
  },
  MC: {
    fmt: '%N%n%O%n%A%nMC-%Z %C %X',
    zip: '980\\d{2}',
    zipex: '98000',
  },
  MD: {
    fmt: '%N%n%O%n%A%nMD-%Z %C',
    zip: '\\d{4}',
    zipex: '2012',
  },
  ME: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '8\\d{4}',
    zipex: '81257',
  },
  MF: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '9[78][01]\\d{2}',
    zipex: '97100',
  },
  MG: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{3}',
    zipex: '501',
  },
  MH: {
    fmt: '%N%n%O%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'ACNOS',
    zip: '(969[67]\\d)(?:[ \\-](\\d{4}))?',
    zipex: '96960',
    regionType: 'state',
    postalType: 'zip',
  },
  MK: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '1314',
  },
  ML: {},
  MM: {
    fmt: '%N%n%O%n%A%n%C, %Z',
    zip: '\\d{5}',
    zipex: '11181',
  },
  MN: {
    fmt: '%N%n%O%n%A%n%C%n%S %Z',
    zip: '\\d{5}',
    zipex: '65030',
    regions: [
      ['Архангай', 'Arkhangai'],
      ['Баян-Өлгий', 'Bayan-Ölgii'],
      ['Баянхонгор', 'Bayankhongor'],
      ['Булган', 'Bulgan'],
      ['Говь-Алтай', 'Govi-Altai'],
      ['Говьсүмбэр', 'Govisümber'],
      ['Дархан-Уул', 'Darkhan-Uul'],
      ['Дорноговь', 'Dornogovi'],
      ['Дорнод', 'Dornod'],
      ['Дундговь', 'Dundgovi'],
      ['Завхан', 'Zavkhan'],
      ['Орхон', 'Orkhon'],
      ['Өвөрхангай', 'Ovorkhangai'],
      ['Өмнөговь', 'Ömnögovi'],
      ['Сүхбаатар', 'Sükhbaatar'],
      ['Сэлэнгэ', 'Selenge'],
      ['Төв', 'Töv'],
      ['Увс', 'Uvs'],
      ['Улаанбаатар', 'Ulaanbaatar'],
      ['Ховд', 'Khovd'],
      ['Хөвсгөл', 'Khovsgol'],
      ['Хэнтий', 'Khentii'],
    ],
  },
  MO: {
    fmt: '%A%n%O%n%N',
    lfmt: '%N%n%O%n%A',
    require: 'A',
  },
  MP: {
    fmt: '%N%n%O%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'ACNOS',
    zip: '(9695[012])(?:[ \\-](\\d{4}))?',
    zipex: '96950',
    regionType: 'state',
    postalType: 'zip',
  },
  MQ: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '9[78]2\\d{2}',
    zipex: '97220',
  },
  MR: {
    upper: 'AC',
  },
  MS: {},
  MT: {
    fmt: '%N%n%O%n%A%n%C %Z',
    upper: 'CZ',
    zip: '[A-Z]{3} ?\\d{2,4}',
    zipex: 'NXR 01',
  },
  MU: {
    fmt: '%N%n%O%n%A%n%Z%n%C',
    upper: 'CZ',
    zip: '\\d{3}(?:\\d{2}|[A-Z]{2}\\d{3})',
    zipex: '42602',
  },
  MV: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{5}',
    zipex: '20026',
  },
  MW: {
    fmt: '%N%n%O%n%A%n%C %X',
  },
  MX: {
    fmt: '%N%n%O%n%A%n%D%n%Z %C, %S',
    require: 'ACSZ',
    upper: 'CSZ',
    zip: '\\d{5}',
    zipex: '02860',
    regionType: 'state',
    regions: [
      ['Ags.', 'Aguascalientes'],
      ['B.C.', 'Baja California'],
      ['B.C.S.', 'Baja California Sur'],
      ['Camp.', 'Campeche'],
      ['Chis.', 'Chiapas'],
      ['Chih.', 'Chihuahua'],
      ['CDMX', 'Ciudad de México'],
      ['Coah.', 'Coahuila de Zaragoza'],
      ['Col.', 'Colima'],
      ['Dgo.', 'Durango'],
      ['Méx.', 'Estado de México'],
      ['Gto.', 'Guanajuato'],
      ['Gro.', 'Guerrero'],
      ['Hgo.', 'Hidalgo'],
      ['Jal.', 'Jalisco'],
      ['Mich.', 'Michoacán'],
      ['Mor.', 'Morelos'],
      ['Nay.', 'Nayarit'],
      ['N.L.', 'Nuevo León'],
      ['Oax.', 'Oaxaca'],
      ['Pue.', 'Puebla'],
      ['Qro.', 'Querétaro'],
      ['Q.R.', 'Quintana Roo'],
      ['S.L.P.', 'San Luis Potosí'],
      ['Sin.', 'Sinaloa'],
      ['Son.', 'Sonora'],
      ['Tab.', 'Tabasco'],
      ['Tamps.', 'Tamaulipas'],
      ['Tlax.', 'Tlaxcala'],
      ['Ver.', 'Veracruz'],
      ['Yuc.', 'Yucatán'],
      ['Zac.', 'Zacatecas'],
    ],
  },
  MZ: {
    fmt: '%N%n%O%n%A%n%Z %C%S',
    zip: '\\d{4}',
    zipex: '1102',
    regions: [
      ['Cabo Delgado', 'Cabo Delgado'],
      ['Cidade de Maputo', 'Cidade de Maputo'],
      ['Gaza', 'Gaza'],
      ['Inhambane', 'Inhambane'],
      ['Manica', 'Manica'],
      ['Maputo', 'Maputo'],
      ['Nampula', 'Nampula'],
      ['Niassa', 'Niassa'],
      ['Sofala', 'Sofala'],
      ['Tete', 'Tete'],
      ['Zambezia', 'Zambezia'],
    ],
  },
  NA: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: '\\d{5}',
    zipex: '10001',
  },
  NC: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '988\\d{2}',
    zipex: '98814',
  },
  NE: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '8001',
  },
  NF: {
    fmt: '%O%n%N%n%A%n%C %S %Z',
    upper: 'CS',
    zip: '2899',
    zipex: '2899',
  },
  NG: {
    fmt: '%N%n%O%n%A%n%D%n%C %Z%n%S',
    upper: 'CS',
    zip: '\\d{6}',
    zipex: '930283',
    regionType: 'state',
    regions: [
      ['Abia', 'Abia'],
      ['Adamawa', 'Adamawa'],
      ['Akwa Ibom', 'Akwa Ibom'],
      ['Anambra', 'Anambra'],
      ['Bauchi', 'Bauchi'],
      ['Bayelsa', 'Bayelsa'],
      ['Benue', 'Benue'],
      ['Borno', 'Borno'],
      ['Cross River', 'Cross River'],
      ['Delta', 'Delta'],
      ['Ebonyi', 'Ebonyi'],
      ['Edo', 'Edo'],
      ['Ekiti', 'Ekiti'],
      ['Enugu', 'Enugu'],
      ['Federal Capital Territory', 'Federal Capital Territory'],
      ['Gombe', 'Gombe'],
      ['Imo', 'Imo'],
      ['Jigawa', 'Jigawa'],
      ['Kaduna', 'Kaduna'],
      ['Kano', 'Kano'],
      ['Katsina', 'Katsina'],
      ['Kebbi', 'Kebbi'],
      ['Kogi', 'Kogi'],
      ['Kwara', 'Kwara'],
      ['Lagos', 'Lagos'],
      ['Nasarawa', 'Nasarawa'],
      ['Niger', 'Niger'],
      ['Ogun State', 'Ogun State'],
      ['Ondo', 'Ondo'],
      ['Osun', 'Osun'],
      ['Oyo', 'Oyo'],
      ['Plateau', 'Plateau'],
      ['Rivers', 'Rivers'],
      ['Sokoto', 'Sokoto'],
      ['Taraba', 'Taraba'],
      ['Yobe', 'Yobe'],
      ['Zamfara', 'Zamfara'],
    ],
  },
  NI: {
    fmt: '%N%n%O%n%A%n%Z%n%C, %S',
    upper: 'CS',
    zip: '\\d{5}',
    zipex: '52000',
    regionType: 'department',
    regions: [
      ['Boaco', 'Boaco'],
      ['Carazo', 'Carazo'],
      ['Chinandega', 'Chinandega'],
      ['Chontales', 'Chontales'],
      ['Estelí', 'Estelí'],
      ['Granada', 'Granada'],
      ['Jinotega', 'Jinotega'],
      ['León', 'León'],
      ['Madriz', 'Madriz'],
      ['Managua', 'Managua'],
      ['Masaya', 'Masaya'],
      ['Matagalpa', 'Matagalpa'],
      ['Nueva Segovia', 'Nueva Segovia'],
      ['Región Autónoma de la Costa Caribe Norte', 'Región Autónoma de la Costa Caribe Norte'],
      ['Región Autónoma de la Costa Caribe Sur', 'Región Autónoma de la Costa Caribe Sur'],
      ['Río San Juan', 'Río San Juan'],
      ['Rivas', 'Rivas'],
    ],
  },
  NL: {
    fmt: '%O%n%N%n%A%n%Z %C',
    require: 'ACZ',
    zip: '[1-9]\\d{3} ?(?:[A-RT-Z][A-Z]|S[BCE-RT-Z])',
    zipex: '1234 AB',
  },
  NO: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '0025',
    cityType: 'post_town',
  },
  NP: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{5}',
    zipex: '44601',
  },
  NR: {
    fmt: '%N%n%O%n%A%n%S',
    require: 'AS',
    regionType: 'district',
    regions: [
      ['Aiwo District', 'Aiwo District'],
      ['Anabar District', 'Anabar District'],
      ['Anetan District', 'Anetan District'],
      ['Anibare District', 'Anibare District'],
      ['Baiti District', 'Baiti District'],
      ['Boe District', 'Boe District'],
      ['Buada District', 'Buada District'],
      ['Denigomodu District', 'Denigomodu District'],
      ['Ewa District', 'Ewa District'],
      ['Ijuw District', 'Ijuw District'],
      ['Meneng District', 'Meneng District'],
      ['Nibok District', 'Nibok District'],
      ['Uaboe District', 'Uaboe District'],
      ['Yaren District', 'Yaren District'],
    ],
  },
  NU: {},
  NZ: {
    fmt: '%N%n%O%n%A%n%D%n%C %Z',
    require: 'ACDZ',
    zip: '\\d{4}',
    zipex: '6001',
  },
  OM: {
    fmt: '%N%n%O%n%A%n%Z%n%C',
    zip: '(?:PC )?\\d{3}',
    zipex: '133',
  },
  PA: {
    fmt: '%N%n%O%n%A%n%C%n%S',
    upper: 'CS',
    regions: [
      ['Bocas del Toro', 'Bocas del Toro'],
      ['Chiriquí', 'Chiriquí'],
      ['Coclé', 'Coclé'],
      ['Colón', 'Colón'],
      ['Darién', 'Darién'],
      ['Emberá', 'Emberá'],
      ['Guna Yala', 'Guna Yala'],
      ['Herrera', 'Herrera'],
      ['Los Santos', 'Los Santos'],
      ['Naso Tjër Di', 'Naso Tjër Di'],
      ['Ngäbe-Buglé', 'Ngäbe-Buglé'],
      ['Panamá', 'Panamá'],
      ['Panamá Oeste', 'Panamá Oeste'],
      ['Veraguas', 'Veraguas'],
    ],
  },
  PE: {
    fmt: '%N%n%O%n%A%n%C %Z%n%S',
    zip: '(?:LIMA \\d{1,2}|CALLAO 0?\\d)|[0-2]\\d{4}',
    zipex: 'LIMA 23',
    cityType: 'district',
    regions: [
      ['Amazonas', 'Amazonas'],
      ['Áncash', 'Áncash'],
      ['Apurímac', 'Apurímac'],
      ['Arequipa', 'Arequipa'],
      ['Ayacucho', 'Ayacucho'],
      ['Cajamarca', 'Cajamarca'],
      ['Callao', 'Callao'],
      ['Cuzco', 'Cuzco'],
      ['Gobierno Regional de Lima', 'Gobierno Regional de Lima'],
      ['Huancavelica', 'Huancavelica'],
      ['Huánuco', 'Huánuco'],
      ['Ica', 'Ica'],
      ['Junín', 'Junín'],
      ['La Libertad', 'La Libertad'],
      ['Lambayeque', 'Lambayeque'],
      ['Loreto', 'Loreto'],
      ['Madre de Dios', 'Madre de Dios'],
      ['Moquegua', 'Moquegua'],
      ['Municipalidad Metropolitana de Lima', 'Municipalidad Metropolitana de Lima'],
      ['Pasco', 'Pasco'],
      ['Piura', 'Piura'],
      ['Puno', 'Puno'],
      ['San Martín', 'San Martín'],
      ['Tacna', 'Tacna'],
      ['Tumbes', 'Tumbes'],
      ['Ucayali', 'Ucayali'],
    ],
  },
  PF: {
    fmt: '%N%n%O%n%A%n%Z %C %S',
    require: 'ACSZ',
    upper: 'CS',
    zip: '987\\d{2}',
    zipex: '98709',
    regionType: 'island',
  },
  PG: {
    fmt: '%N%n%O%n%A%n%C %Z %S',
    require: 'ACS',
    zip: '\\d{3}',
    zipex: '111',
    regions: [
      ['Bougainville', 'Bougainville'],
      ['Central Provins', 'Central Provins'],
      ['Enga Provins', 'Enga Provins'],
      ['Gulf Provins', 'Gulf Provins'],
      ['Hela Provins', 'Hela Provins'],
      ['Is Niu Briten Provins', 'Is Niu Briten Provins'],
      ['Is Sepik Provins', 'Is Sepik Provins'],
      ['Isten Hailans Provins', 'Isten Hailans Provins'],
      ['Jiwaka Provins', 'Jiwaka Provins'],
      ['Madang Provins', 'Madang Provins'],
      ['Manus Provins', 'Manus Provins'],
      ['Milen Be Provins', 'Milen Be Provins'],
      ['Morobe Provins', 'Morobe Provins'],
      ['Nesenel Kapitol Distrik', 'Nesenel Kapitol Distrik'],
      ['Niu Ailan Provins', 'Niu Ailan Provins'],
      ['Oro Provins', 'Oro Provins'],
      ['Sandaun Provins', 'Sandaun Provins'],
      ['Sauten Hailans Provins', 'Sauten Hailans Provins'],
      ['Simbu Provins', 'Simbu Provins'],
      ['Wes Niu Briten Provins', 'Wes Niu Briten Provins'],
      ['Western Hailans Provins', 'Western Hailans Provins'],
      ['Western Provins', 'Western Provins'],
    ],
  },
  PH: {
    fmt: '%N%n%O%n%A%n%D, %C%n%Z %S',
    zip: '\\d{4}',
    zipex: '1008',
    regions: [
      ['Abra', 'Abra'],
      ['Agusan del Norte', 'Agusan del Norte'],
      ['Agusan del Sur', 'Agusan del Sur'],
      ['Aklan', 'Aklan'],
      ['Albay', 'Albay'],
      ['Antique', 'Antique'],
      ['Apayao', 'Apayao'],
      ['Aurora', 'Aurora'],
      ['Basilan', 'Basilan'],
      ['Bataan', 'Bataan'],
      ['Batanes', 'Batanes'],
      ['Batangas', 'Batangas'],
      ['Benguet', 'Benguet'],
      ['Biliran', 'Biliran'],
      ['Bohol', 'Bohol'],
      ['Bukidnon', 'Bukidnon'],
      ['Bulacan', 'Bulacan'],
      ['Cagayan', 'Cagayan'],
      ['Camarines Norte', 'Camarines Norte'],
      ['Camarines Sur', 'Camarines Sur'],
      ['Camiguin', 'Camiguin'],
      ['Capiz', 'Capiz'],
      ['Catanduanes', 'Catanduanes'],
      ['Cavite', 'Cavite'],
      ['Cebu', 'Cebu'],
      ['Compostela Valley', 'Compostela Valley'],
      ['Cotabato', 'Cotabato'],
      ['Davao del Norte', 'Davao del Norte'],
      ['Davao del Sur', 'Davao del Sur'],
      ['Davao Occidental', 'Davao Occidental'],
      ['Davao Oriental', 'Davao Oriental'],
      ['Dinagat Islands', 'Dinagat Islands'],
      ['Eastern Samar', 'Eastern Samar'],
      ['Guimaras', 'Guimaras'],
      ['Ifugao', 'Ifugao'],
      ['Ilocos Norte', 'Ilocos Norte'],
      ['Ilocos Sur', 'Ilocos Sur'],
      ['Iloilo', 'Iloilo'],
      ['Isabela', 'Isabela'],
      ['Kalinga', 'Kalinga'],
      ['La Union', 'La Union'],
      ['Laguna', 'Laguna'],
      ['Lanao del Norte', 'Lanao del Norte'],
      ['Lanao del Sur', 'Lanao del Sur'],
      ['Leyte', 'Leyte'],
      ['Maguindanao', 'Maguindanao'],
      ['Marinduque', 'Marinduque'],
      ['Masbate', 'Masbate'],
      ['Metro Manila', 'Metro Manila'],
      ['Mindoro Occidental', 'Mindoro Occidental'],
      ['Mindoro Oriental', 'Mindoro Oriental'],
      ['Misamis Occidental', 'Misamis Occidental'],
      ['Misamis Oriental', 'Misamis Oriental'],
      ['Mountain Province', 'Mountain Province'],
      ['Negros Occidental', 'Negros Occidental'],
      ['Negros Oriental', 'Negros Oriental'],
      ['Northern Samar', 'Northern Samar'],
      ['Nueva Ecija', 'Nueva Ecija'],
      ['Nueva Vizcaya', 'Nueva Vizcaya'],
      ['Palawan', 'Palawan'],
      ['Pampanga', 'Pampanga'],
      ['Pangasinan', 'Pangasinan'],
      ['Quezon Province', 'Quezon Province'],
      ['Quirino', 'Quirino'],
      ['Rizal', 'Rizal'],
      ['Romblon', 'Romblon'],
      ['Samar', 'Samar'],
      ['Sarangani', 'Sarangani'],
      ['Siquijor', 'Siquijor'],
      ['Sorsogon', 'Sorsogon'],
      ['South Cotabato', 'South Cotabato'],
      ['Southern Leyte', 'Southern Leyte'],
      ['Sultan Kudarat', 'Sultan Kudarat'],
      ['Sulu', 'Sulu'],
      ['Surigao del Norte', 'Surigao del Norte'],
      ['Surigao del Sur', 'Surigao del Sur'],
      ['Tarlac', 'Tarlac'],
      ['Tawi-Tawi', 'Tawi-Tawi'],
      ['Zambales', 'Zambales'],
      ['Zamboanga del Norte', 'Zamboanga del Norte'],
      ['Zamboanga del Sur', 'Zamboanga del Sur'],
      ['Zamboanga Sibuguey', 'Zamboanga Sibuguey'],
    ],
  },
  PK: {
    fmt: '%N%n%O%n%A%n%D%n%C-%Z',
    zip: '\\d{5}',
    zipex: '44000',
  },
  PL: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{2}-\\d{3}',
    zipex: '00-950',
  },
  PM: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '9[78]5\\d{2}',
    zipex: '97500',
  },
  PR: {
    fmt: '%N%n%O%n%A%n%C PR %Z',
    require: 'ACZ',
    upper: 'ACNO',
    zip: '(00[679]\\d{2})(?:[ \\-](\\d{4}))?',
    zipex: '00930',
    postalType: 'zip',
  },
  PS: {},
  PT: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{4}-\\d{3}',
    zipex: '2725-079',
  },
  PW: {
    fmt: '%N%n%O%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'ACNOS',
    zip: '(969(?:39|40))(?:[ \\-](\\d{4}))?',
    zipex: '96940',
    regionType: 'state',
    postalType: 'zip',
    regions: [
      ['Aimeliik', 'Aimeliik'],
      ['Airai', 'Airai'],
      ['Angaur', 'Angaur'],
      ['Hatohobei', 'Hatohobei'],
      ['Kayangel', 'Kayangel'],
      ['Koror', 'Koror'],
      ['Melekeok', 'Melekeok'],
      ['Ngaraard', 'Ngaraard'],
      ['Ngarchelong', 'Ngarchelong'],
      ['Ngardmau', 'Ngardmau'],
      ['Ngaremlengui', 'Ngaremlengui'],
      ['Ngatpang', 'Ngatpang'],
      ['Ngchesar', 'Ngchesar'],
      ['Ngiwal', 'Ngiwal'],
      ['Peleliu', 'Peleliu'],
      ['Sonsorol', 'Sonsorol'],
    ],
  },
  PY: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{6}',
    zipex: '001001',
  },
  QA: {
    upper: 'AC',
  },
  RE: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '9[78]4\\d{2}',
    zipex: '97400',
  },
  RO: {
    fmt: '%N%n%O%n%A%n%Z %S %C',
    require: 'ACZ',
    upper: 'AC',
    zip: '\\d{6}',
    zipex: '060274',
    regions: [
      ['Alba', 'Alba'],
      ['Arad', 'Arad'],
      ['Argeș', 'Argeș'],
      ['Bacău', 'Bacău'],
      ['Bihor', 'Bihor'],
      ['Bistrița-Năsăud', 'Bistrița-Năsăud'],
      ['Botoșani', 'Botoșani'],
      ['Brașov', 'Brașov'],
      ['Brăila', 'Brăila'],
      ['București', 'București'],
      ['Buzău', 'Buzău'],
      ['Caraș-Severin', 'Caraș-Severin'],
      ['Călărași', 'Călărași'],
      ['Cluj', 'Cluj'],
      ['Constanța', 'Constanța'],
      ['Covasna', 'Covasna'],
      ['Dâmbovița', 'Dâmbovița'],
      ['Dolj', 'Dolj'],
      ['Galați', 'Galați'],
      ['Giurgiu', 'Giurgiu'],
      ['Gorj', 'Gorj'],
      ['Harghita', 'Harghita'],
      ['Hunedoara', 'Hunedoara'],
      ['Ialomița', 'Ialomița'],
      ['Iași', 'Iași'],
      ['Ilfov', 'Ilfov'],
      ['Maramureș', 'Maramureș'],
      ['Mehedinți', 'Mehedinți'],
      ['Mureș', 'Mureș'],
      ['Neamț', 'Neamț'],
      ['Olt', 'Olt'],
      ['Prahova', 'Prahova'],
      ['Satu Mare', 'Satu Mare'],
      ['Sălaj', 'Sălaj'],
      ['Sibiu', 'Sibiu'],
      ['Suceava', 'Suceava'],
      ['Teleorman', 'Teleorman'],
      ['Timiș', 'Timiș'],
      ['Tulcea', 'Tulcea'],
      ['Vaslui', 'Vaslui'],
      ['Vâlcea', 'Vâlcea'],
      ['Vrancea', 'Vrancea'],
    ],
  },
  RS: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5,6}',
    zipex: '106314',
  },
  RU: {
    fmt: '%N%n%O%n%A%n%C%n%S%n%Z',
    lfmt: '%N%n%O%n%A%n%C%n%S%n%Z',
    require: 'ACSZ',
    upper: 'AC',
    zip: '\\d{6}',
    zipex: '247112',
    regionType: 'oblast',
    regions: [
      ['Алтайский край', 'Altayskiy kray'],
      ['Амурская область', "Amurskaya oblast'"],
      ['Архангельская область', "Arkhangelskaya oblast'"],
      ['Астраханская область', "Astrakhanskaya oblast'"],
      ['Белгородская область', "Belgorodskaya oblast'"],
      ['Брянская область', "Bryanskaya oblast'"],
      ['Владимирская область', "Vladimirskaya oblast'"],
      ['Волгоградская область', "Volgogradskaya oblast'"],
      ['Вологодская область', "Vologodskaya oblast'"],
      ['Воронежская область', "Voronezhskaya oblast'"],
      ['Еврейская автономная область', "Evreyskaya avtonomnaya oblast'"],
      ['Забайкальский край', 'Zabaykalskiy kray'],
      ['Ивановская область', "Ivanovskaya oblast'"],
      ['Иркутская область', "Irkutskaya oblast'"],
      ['Кабардино-Балкарская Республика', 'Kabardino-Balkarskaya Republits'],
      ['Калининградская область', "Kaliningradskaya oblast'"],
      ['Калужская область', "Kaluzhskaya oblast'"],
      ['Камчатский край', 'Kamchatskiy kray'],
      ['Карачаево-Черкесская Республика', 'Karachaevo-Cherkesskaya Republits'],
      ['Кемеровская область', "Kemerovskaya oblast'"],
      ['Кировская область', "Kirovskaya oblast'"],
      ['Костромская область', "Kostromskaya oblast'"],
      ['Краснодарский край', 'Krasnodarskiy kray'],
      ['Красноярский край', 'Krasnoyarskiy kray'],
      ['Курганская область', "Kurganskaya oblast'"],
      ['Курская область', "Kurskaya oblast'"],
      ['Ленинградская область', "Leningradskaya oblast'"],
      ['Липецкая область', "Lipetskaya oblast'"],
      ['Магаданская область', "Magadanskaya oblast'"],
      ['Москва', 'Moskva'],
      ['Московская область', "Moskovskaya oblast'"],
      ['Мурманская область', "Murmanskaya oblast'"],
      ['Ненецкий автономный округ', 'Nenetskiy'],
      ['Нижегородская область', "Nizhegorodskaya oblast'"],
      ['Новгородская область', "Novgorodskaya oblast'"],
      ['Новосибирская область', "Novosibirskaya oblast'"],
      ['Омская область', "Omskaya oblast'"],
      ['Оренбургская область', "Orenburgskaya oblast'"],
      ['Орловская область', "Orlovskaya oblast'"],
      ['Пензенская область', "Penzenskaya oblast'"],
      ['Пермский край', 'Permskiy kray'],
      ['Приморский край', 'Primorskiy kray'],
      ['Псковская область', "Pskovskaya oblast'"],
      ['Республика Адыгея', 'Respublika Adygeya'],
      ['Республика Алтай', 'Altay Republits'],
      ['Республика Башкортостан', 'Bashkortostan Republits'],
      ['Республика Бурятия', 'Buryatiya Republits'],
      ['Республика Дагестан', 'Dagestan Republits'],
      ['Республика Ингушетия', 'Ingushetiya Republits'],
      ['Республика Калмыкия', 'Respublika Kalmykiya'],
      ['Республика Карелия', 'Kareliya Republits'],
      ['Республика Коми', 'Komi Republits'],
      ['Автономна Республіка Крим', 'Respublika Krym'],
      ['Республика Марий Эл', 'Respublika Mariy El'],
      ['Республика Мордовия', 'Respublika Mordoviya'],
      ['Республика Саха (Якутия)', 'Sakha (Yakutiya) Republits'],
      ['Республика Северная Осетия-Алания', 'Respublika Severnaya Osetiya-Alaniya'],
      ['Республика Татарстан', 'Respublika Tatarstan'],
      ['Республика Тыва', 'Tyva Republits'],
      ['Республика Удмуртия', 'Udmurtskaja Respublika'],
      ['Республика Хакасия', 'Khakasiya Republits'],
      ['Ростовская область', "Rostovskaya oblast'"],
      ['Рязанская область', "Ryazanskaya oblast'"],
      ['Самарская область', "Samarskaya oblast'"],
      ['Санкт-Петербург', 'Sankt-Peterburg'],
      ['Саратовская область', "Saratovskaya oblast'"],
      ['Сахалинская область', "Sakhalinskaya oblast'"],
      ['Свердловская область', "Sverdlovskaya oblast'"],
      ['Севастополь', "Sevastopol'"],
      ['Смоленская область', "Smolenskaya oblast'"],
      ['Ставропольский край', 'Stavropolskiy kray'],
      ['Тамбовская область', "Tambovskaya oblast'"],
      ['Тверская область', "Tverskaya oblast'"],
      ['Томская область', "Tomskaya oblast'"],
      ['Тульская область', "Tulskaya oblast'"],
      ['Тюменская область', "Tyumenskaya oblast'"],
      ['Ульяновская область', "Ulyanovskaya oblast'"],
      ['Хабаровский край', 'Khabarovskiy kray'],
      ['Ханты-Мансийский автономный округ', 'Khanty-Mansiyskiy avtonomnyy okrug'],
      ['Челябинская область', "Chelyabinskaya oblast'"],
      ['Чеченская Республика', 'Chechenskaya Republits'],
      ['Чувашская Республика', 'Chuvashia'],
      ['Чукотский автономный округ', 'Chukotskiy'],
      ['Ямало-Ненецкий автономный округ', 'Yamalo-Nenetskiy'],
      ['Ярославская область', "Yaroslavskaya oblast'"],
    ],
  },
  RW: {
    upper: 'AC',
  },
  SA: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: '\\d{5}',
    zipex: '11564',
  },
  SB: {},
  SC: {
    fmt: '%N%n%O%n%A%n%C%n%S',
    upper: 'S',
    regionType: 'island',
  },
  SD: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: '\\d{5}',
    zipex: '11042',
    cityType: 'district',
  },
  SE: {
    fmt: '%O%n%N%n%A%nSE-%Z %C',
    require: 'ACZ',
    zip: '\\d{3} ?\\d{2}',
    zipex: '11455',
    cityType: 'post_town',
  },
  SG: {
    fmt: '%N%n%O%n%A%nSINGAPORE %Z',
    require: 'AZ',
    zip: '\\d{6}',
    zipex: '546080',
  },
  SH: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: '(?:ASCN|STHL) 1ZZ',
    zipex: 'STHL 1ZZ',
  },
  SI: {
    fmt: '%N%n%O%n%A%nSI-%Z %C',
    zip: '\\d{4}',
    zipex: '4000',
  },
  SJ: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '9170',
    cityType: 'post_town',
  },
  SK: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'ACZ',
    zip: '\\d{3} ?\\d{2}',
    zipex: '010 01',
  },
  SL: {},
  SM: {
    fmt: '%N%n%O%n%A%n%Z %C',
    require: 'AZ',
    zip: '4789\\d',
    zipex: '47890',
  },
  SN: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '12500',
  },
  SO: {
    fmt: '%N%n%O%n%A%n%C, %S %Z',
    require: 'ACS',
    upper: 'ACS',
    zip: '[A-Z]{2} ?\\d{5}',
    zipex: 'JH 09010',
    regions: [
      ['AD', 'Awdal'],
      ['BK', 'Bakool'],
      ['BN', 'Banaadir'],
      ['BR', 'Bari'],
      ['BY', 'Bay'],
      ['GG', 'Galguduud'],
      ['GD', 'Gedo'],
      ['HR', 'Hiiraan'],
      ['JD', 'Jubbada Dhexe'],
      ['JH', 'Jubbada Hoose'],
      ['MD', 'Mudug'],
      ['NG', 'Nugaal'],
      ['SG', 'Sanaag'],
      ['SD', 'Shabeellaha Dhexe'],
      ['SH', 'Shabeellaha Hoose'],
      ['SL', 'Sool'],
      ['TG', 'Togdheer'],
      ['WG', 'Woqooyi Galbeed'],
    ],
  },
  SR: {
    fmt: '%N%n%O%n%A%n%C%n%S',
    upper: 'AS',
    regions: [
      ['Brokopondo', 'Brokopondo'],
      ['Commewijne', 'Commewijne'],
      ['Coronie', 'Coronie'],
      ['Marowijne', 'Marowijne'],
      ['Nickerie', 'Nickerie'],
      ['Para', 'Para'],
      ['Paramaribo', 'Paramaribo'],
      ['Saramacca', 'Saramacca'],
      ['Sipaliwini', 'Sipaliwini'],
      ['Wanica', 'Wanica'],
    ],
  },
  SS: {},
  ST: {},
  SV: {
    fmt: '%N%n%O%n%A%n%Z-%C%n%S',
    require: 'ACS',
    upper: 'CSZ',
    zip: '[1-3][1-7][0-2]\\d',
    zipex: '1101',
    regions: [
      ['Ahuachapan', 'Ahuachapán'],
      ['Cabanas', 'Cabañas'],
      ['Calatenango', 'Chalatenango'],
      ['Cuscatlan', 'Cuscatlán'],
      ['La Libertad', 'La Libertad'],
      ['La Paz', 'La Paz'],
      ['La Union', 'La Unión'],
      ['Morazan', 'Morazán'],
      ['San Miguel', 'San Miguel'],
      ['San Salvador', 'San Salvador'],
      ['San Vicente', 'San Vicente'],
      ['Santa Ana', 'Santa Ana'],
      ['Sonsonate', 'Sonsonate'],
      ['Usulutan', 'Usulután'],
    ],
  },
  SX: {},
  SZ: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    upper: 'ACZ',
    zip: '[HLMS]\\d{3}',
    zipex: 'H100',
  },
  TA: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: 'TDCU 1ZZ',
    zipex: 'TDCU 1ZZ',
  },
  TC: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    require: 'ACZ',
    upper: 'CZ',
    zip: 'TKCA 1ZZ',
    zipex: 'TKCA 1ZZ',
  },
  TD: {},
  TG: {},
  TH: {
    fmt: '%N%n%O%n%A%n%D %C%n%S %Z',
    lfmt: '%N%n%O%n%A%n%D, %C%n%S %Z',
    upper: 'S',
    zip: '\\d{5}',
    zipex: '10150',
    regions: [
      ['กระบี่', 'Krabi'],
      ['กรุงเทพมหานคร', 'Bangkok'],
      ['กาญจนบุรี', 'Kanchanaburi'],
      ['กาฬสินธุ์', 'Kalasin'],
      ['กำแพงเพชร', 'Kamphaeng Phet'],
      ['ขอนแก่น', 'Khon Kaen'],
      ['จังหวัด บึงกาฬ', 'Bueng Kan'],
      ['จันทบุรี', 'Chanthaburi'],
      ['ฉะเชิงเทรา', 'Chachoengsao'],
      ['ชลบุรี', 'Chon Buri'],
      ['ชัยนาท', 'Chai Nat'],
      ['ชัยภูมิ', 'Chaiyaphum'],
      ['ชุมพร', 'Chumpon'],
      ['เชียงราย', 'Chiang Rai'],
      ['เชียงใหม่', 'Chiang Mai'],
      ['ตรัง', 'Trang'],
      ['ตราด', 'Trat'],
      ['ตาก', 'Tak'],
      ['นครนายก', 'Nakhon Nayok'],
      ['นครปฐม', 'Nakhon Pathom'],
      ['นครพนม', 'Nakhon Phanom'],
      ['นครราชสีมา', 'Nakhon Ratchasima'],
      ['นครศรีธรรมราช', 'Nakhon Si Thammarat'],
      ['นครสวรรค์', 'Nakhon Sawan'],
      ['นนทบุรี', 'Nonthaburi'],
      ['นราธิวาส', 'Narathiwat'],
      ['น่าน', 'Nan'],
      ['บุรีรัมย์', 'Buri Ram'],
      ['ปทุมธานี', 'Pathum Thani'],
      ['ประจวบคีรีขันธ์', 'Prachuap Khiri Khan'],
      ['ปราจีนบุรี', 'Prachin Buri'],
      ['ปัตตานี', 'Pattani'],
      ['พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya'],
      ['พะเยา', 'Phayao'],
      ['พังงา', 'Phang Nga'],
      ['พัทลุง', 'Phattalung'],
      ['พิจิตร', 'Phichit'],
      ['พิษณุโลก', 'Phitsanulok'],
      ['เพชรบุรี', 'Phetchaburi'],
      ['เพชรบูรณ์', 'Phetchabun'],
      ['แพร่', 'Phrae'],
      ['ภูเก็ต', 'Phuket'],
      ['มหาสารคาม', 'Maha Sarakham'],
      ['มุกดาหาร', 'Mukdahan'],
      ['แม่ฮ่องสอน', 'Mae Hong Son'],
      ['ยโสธร', 'Yasothon'],
      ['ยะลา', 'Yala'],
      ['ร้อยเอ็ด', 'Roi Et'],
      ['ระนอง', 'Ranong'],
      ['ระยอง', 'Rayong'],
      ['ราชบุรี', 'Ratchaburi'],
      ['ลพบุรี', 'Lop Buri'],
      ['ลำปาง', 'Lampang'],
      ['ลำพูน', 'Lamphun'],
      ['เลย', 'Loei'],
      ['ศรีสะเกษ', 'Si Sa Ket'],
      ['สกลนคร', 'Sakon Nakhon'],
      ['สงขลา', 'Songkhla'],
      ['สตูล', 'Satun'],
      ['สมุทรปราการ', 'Samut Prakan'],
      ['สมุทรสงคราม', 'Samut Songkhram'],
      ['สมุทรสาคร', 'Samut Sakhon'],
      ['สระแก้ว', 'Sa Kaeo'],
      ['สระบุรี', 'Saraburi'],
      ['สิงห์บุรี', 'Sing Buri'],
      ['สุโขทัย', 'Sukhothai'],
      ['สุพรรณบุรี', 'Suphanburi'],
      ['สุราษฎร์ธานี', 'Surat Thani'],
      ['สุรินทร์', 'Surin'],
      ['หนองคาย', 'Nong Khai'],
      ['หนองบัวลำภู', 'Nong Bua Lam Phu'],
      ['อ่างทอง', 'Ang Thong'],
      ['อำนาจเจริญ', 'Amnat Charoen'],
      ['อุดรธานี', 'Udon Thani'],
      ['อุตรดิตถ์', 'Uttaradit'],
      ['อุทัยธานี', 'Uthai Thani'],
      ['อุบลราชธานี', 'Ubon Ratchathani'],
    ],
  },
  TJ: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{6}',
    zipex: '735450',
  },
  TK: {},
  TL: {},
  TM: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{6}',
    zipex: '744000',
  },
  TN: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4}',
    zipex: '1002',
  },
  TO: {},
  TR: {
    fmt: '%N%n%O%n%A%n%Z %C/%S',
    require: 'ACZ',
    zip: '\\d{5}',
    zipex: '01960',
    cityType: 'district',
    regions: [
      ['Adana', 'Adana'],
      ['Adıyaman', 'Adıyaman'],
      ['Afyon', 'Afyon'],
      ['Ağrı', 'Ağrı'],
      ['Aksaray', 'Aksaray'],
      ['Amasya', 'Amasya'],
      ['Ankara', 'Ankara'],
      ['Antalya', 'Antalya'],
      ['Ardahan', 'Ardahan'],
      ['Artvin', 'Artvin'],
      ['Aydın', 'Aydın'],
      ['Balıkesir', 'Balıkesir'],
      ['Bartın', 'Bartın'],
      ['Batman', 'Batman'],
      ['Bayburt', 'Bayburt'],
      ['Bilecik', 'Bilecik'],
      ['Bingöl', 'Bingöl'],
      ['Bitlis', 'Bitlis'],
      ['Bolu', 'Bolu'],
      ['Burdur', 'Burdur'],
      ['Bursa', 'Bursa'],
      ['Çanakkale', 'Çanakkale'],
      ['Çankırı', 'Çankırı'],
      ['Çorum', 'Çorum'],
      ['Denizli', 'Denizli'],
      ['Diyarbakır', 'Diyarbakır'],
      ['Düzce', 'Düzce'],
      ['Edirne', 'Edirne'],
      ['Elazığ', 'Elazığ'],
      ['Erzincan', 'Erzincan'],
      ['Erzurum', 'Erzurum'],
      ['Eskişehir', 'Eskişehir'],
      ['Gaziantep', 'Gaziantep'],
      ['Giresun', 'Giresun'],
      ['Gümüşhane', 'Gümüşhane'],
      ['Hakkari', 'Hakkari'],
      ['Hatay', 'Hatay'],
      ['Iğdır', 'Iğdır'],
      ['Isparta', 'Isparta'],
      ['İstanbul', 'İstanbul'],
      ['İzmir', 'İzmir'],
      ['Kahramanmaraş', 'Kahramanmaraş'],
      ['Karabük', 'Karabük'],
      ['Karaman', 'Karaman'],
      ['Kars', 'Kars'],
      ['Kastamonu', 'Kastamonu'],
      ['Kayseri', 'Kayseri'],
      ['Kırıkkale', 'Kırıkkale'],
      ['Kırklareli', 'Kırklareli'],
      ['Kırşehir', 'Kırşehir'],
      ['Kilis', 'Kilis'],
      ['Kocaeli', 'Kocaeli'],
      ['Konya', 'Konya'],
      ['Kütahya', 'Kütahya'],
      ['Malatya', 'Malatya'],
      ['Manisa', 'Manisa'],
      ['Mardin', 'Mardin'],
      ['Mersin', 'Mersin'],
      ['Muğla', 'Muğla'],
      ['Muş', 'Muş'],
      ['Nevşehir', 'Nevşehir'],
      ['Niğde', 'Niğde'],
      ['Ordu', 'Ordu'],
      ['Osmaniye', 'Osmaniye'],
      ['Rize', 'Rize'],
      ['Sakarya', 'Sakarya'],
      ['Samsun', 'Samsun'],
      ['Siirt', 'Siirt'],
      ['Sinop', 'Sinop'],
      ['Sivas', 'Sivas'],
      ['Şanlıurfa', 'Şanlıurfa'],
      ['Şırnak', 'Şırnak'],
      ['Tekirdağ', 'Tekirdağ'],
      ['Tokat', 'Tokat'],
      ['Trabzon', 'Trabzon'],
      ['Tunceli', 'Tunceli'],
      ['Uşak', 'Uşak'],
      ['Van', 'Van'],
      ['Yalova', 'Yalova'],
      ['Yozgat', 'Yozgat'],
      ['Zonguldak', 'Zonguldak'],
    ],
  },
  TT: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    zip: '\\d{6}',
    zipex: '500234',
  },
  TV: {
    fmt: '%N%n%O%n%A%n%C%n%S',
    upper: 'ACS',
    regionType: 'island',
    regions: [
      ['Funafuti', 'Funafuti'],
      ['Nanumanga', 'Nanumanga'],
      ['Nanumea', 'Nanumea'],
      ['Niulakita', 'Niulakita'],
      ['Niutao', 'Niutao'],
      ['Nui', 'Nui'],
      ['Nukufetau', 'Nukufetau'],
      ['Nukulaelae', 'Nukulaelae'],
      ['Vaitupu', 'Vaitupu'],
    ],
  },
  TW: {
    fmt: '%Z%n%S%C%n%A%n%O%n%N',
    lfmt: '%N%n%O%n%A%n%C, %S %Z',
    require: 'ACSZ',
    zip: '\\d{3}(?:\\d{2,3})?',
    zipex: '104',
    regionType: 'county',
    cityType: 'district',
    regions: [
      ['台中市', 'Taichung City'],
      ['台北市', 'Taipei City'],
      ['台東縣', 'Taitung County'],
      ['台南市', 'Tainan City'],
      ['宜蘭縣', 'Yilan County'],
      ['花蓮縣', 'Hualien County'],
      ['金門縣', 'Kinmen County'],
      ['南投縣', 'Nantou County'],
      ['屏東縣', 'Pingtung County'],
      ['苗栗縣', 'Miaoli County'],
      ['桃園市', 'Taoyuan City'],
      ['高雄市', 'Kaohsiung City'],
      ['基隆市', 'Keelung City'],
      ['連江縣', 'Lienchiang County'],
      ['雲林縣', 'Yunlin County'],
      ['新北市', 'New Taipei City'],
      ['新竹市', 'Hsinchu City'],
      ['新竹縣', 'Hsinchu County'],
      ['嘉義市', 'Chiayi City'],
      ['嘉義縣', 'Chiayi County'],
      ['彰化縣', 'Changhua County'],
      ['澎湖縣', 'Penghu County'],
    ],
  },
  TZ: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{4,5}',
    zipex: '6090',
  },
  UA: {
    fmt: '%N%n%O%n%A%n%C%n%S%n%Z',
    lfmt: '%N%n%O%n%A%n%C%n%S%n%Z',
    require: 'ACZ',
    zip: '\\d{5}',
    zipex: '15432',
    regionType: 'oblast',
    regions: [
      ['Автономна Республіка Крим', 'Crimea'],
      ['Вінницька область', "Vinnyts'ka oblast"],
      ['Волинська область', "Volyns'ka oblast"],
      ['Дніпропетровська область', 'Dnipropetrovsk oblast'],
      ['Донецька область', 'Donetsk oblast'],
      ['Житомирська область', "Zhytomyrs'ka oblast"],
      ['Закарпатська область', "Zakarpats'ka oblast"],
      ['Запорізька область', "Zaporiz'ka oblast"],
      ['Івано-Франківська область', "Ivano-Frankivs'ka oblast"],
      ['місто Київ', 'Kyiv city'],
      ['Київська область', 'Kiev oblast'],
      ['Кіровоградська область', "Kirovohrads'ka oblast"],
      ['Луганська область', "Luhans'ka oblast"],
      ['Львівська область', 'Lviv oblast'],
      ['Миколаївська область', "Mykolaivs'ka oblast"],
      ['Одеська область', 'Odessa oblast'],
      ['Полтавська область', "Poltavs'ka oblast"],
      ['Рівненська область', "Rivnens'ka oblast"],
      ['місто Севастополь', "Sevastopol' city"],
      ['Сумська область', "Sums'ka oblast"],
      ['Тернопільська область', "Ternopil's'ka oblast"],
      ['Харківська область', 'Kharkiv oblast'],
      ['Херсонська область', "Khersons'ka oblast"],
      ['Хмельницька область', "Khmel'nyts'ka oblast"],
      ['Черкаська область', "Cherkas'ka oblast"],
      ['Чернівецька область', "Chernivets'ka oblast"],
      ['Чернігівська область', "Chernihivs'ka oblast"],
    ],
  },
  UG: {},
  US: {
    fmt: '%N%n%O%n%A%n%C, %S %Z',
    require: 'ACSZ',
    upper: 'CS',
    zip: '(\\d{5})(?:[ \\-](\\d{4}))?',
    zipex: '95014',
    regionType: 'state',
    postalType: 'zip',
    regions: [
      ['AL', 'Alabama'],
      ['AK', 'Alaska'],
      ['AS', 'American Samoa'],
      ['AZ', 'Arizona'],
      ['AR', 'Arkansas'],
      ['AA', 'Armed Forces (AA)'],
      ['AE', 'Armed Forces (AE)'],
      ['AP', 'Armed Forces (AP)'],
      ['CA', 'California'],
      ['CO', 'Colorado'],
      ['CT', 'Connecticut'],
      ['DE', 'Delaware'],
      ['DC', 'District of Columbia'],
      ['FL', 'Florida'],
      ['GA', 'Georgia'],
      ['GU', 'Guam'],
      ['HI', 'Hawaii'],
      ['ID', 'Idaho'],
      ['IL', 'Illinois'],
      ['IN', 'Indiana'],
      ['IA', 'Iowa'],
      ['KS', 'Kansas'],
      ['KY', 'Kentucky'],
      ['LA', 'Louisiana'],
      ['ME', 'Maine'],
      ['MH', 'Marshall Islands'],
      ['MD', 'Maryland'],
      ['MA', 'Massachusetts'],
      ['MI', 'Michigan'],
      ['FM', 'Micronesia'],
      ['MN', 'Minnesota'],
      ['MS', 'Mississippi'],
      ['MO', 'Missouri'],
      ['MT', 'Montana'],
      ['NE', 'Nebraska'],
      ['NV', 'Nevada'],
      ['NH', 'New Hampshire'],
      ['NJ', 'New Jersey'],
      ['NM', 'New Mexico'],
      ['NY', 'New York'],
      ['NC', 'North Carolina'],
      ['ND', 'North Dakota'],
      ['MP', 'Northern Mariana Islands'],
      ['OH', 'Ohio'],
      ['OK', 'Oklahoma'],
      ['OR', 'Oregon'],
      ['PW', 'Palau'],
      ['PA', 'Pennsylvania'],
      ['PR', 'Puerto Rico'],
      ['RI', 'Rhode Island'],
      ['SC', 'South Carolina'],
      ['SD', 'South Dakota'],
      ['TN', 'Tennessee'],
      ['TX', 'Texas'],
      ['UT', 'Utah'],
      ['VT', 'Vermont'],
      ['VI', 'Virgin Islands'],
      ['VA', 'Virginia'],
      ['WA', 'Washington'],
      ['WV', 'West Virginia'],
      ['WI', 'Wisconsin'],
      ['WY', 'Wyoming'],
    ],
  },
  UY: {
    fmt: '%N%n%O%n%A%n%Z %C %S',
    upper: 'CS',
    zip: '\\d{5}',
    zipex: '11600',
    regions: [
      ['Artigas', 'Artigas'],
      ['Canelones', 'Canelones'],
      ['Cerro Largo', 'Cerro Largo'],
      ['Colonia', 'Colonia'],
      ['Durazno', 'Durazno'],
      ['Flores', 'Flores'],
      ['Florida', 'Florida'],
      ['Lavalleja', 'Lavalleja'],
      ['Maldonado', 'Maldonado'],
      ['Montevideo', 'Montevideo'],
      ['Paysandú', 'Paysandú'],
      ['Río Negro', 'Río Negro'],
      ['Rivera', 'Rivera'],
      ['Rocha', 'Rocha'],
      ['Salto', 'Salto'],
      ['San José', 'San José'],
      ['Soriano', 'Soriano'],
      ['Tacuarembó', 'Tacuarembó'],
      ['Treinta y Tres', 'Treinta y Tres'],
    ],
  },
  UZ: {
    fmt: '%N%n%O%n%A%n%Z %C%n%S',
    upper: 'CS',
    zip: '\\d{6}',
    zipex: '702100',
    regions: [
      ['Andijon Viloyati', 'Andijon Viloyati'],
      ['Buxoro Viloyati', 'Buxoro Viloyati'],
      ["Farg'ona Viloyati", "Farg'ona Viloyati"],
      ['Jizzax Viloyati', 'Jizzax Viloyati'],
      ['Namangan Viloyati', 'Namangan Viloyati'],
      ['Navoiy Viloyati', 'Navoiy Viloyati'],
      ['Qashqadaryo Viloyati', 'Qashqadaryo Viloyati'],
      ['Qoraqalpog’iston Respublikasi', 'Qoraqalpog’iston Respublikasi'],
      ['Samarqand Viloyati', 'Samarqand Viloyati'],
      ['Sirdaryo Viloyati', 'Sirdaryo Viloyati'],
      ['Surxondaryo Viloyati', 'Surxondaryo Viloyati'],
      ['Toshkent', 'Toshkent'],
      ['Toshkent Viloyati', 'Toshkent Viloyati'],
      ['Xorazm Viloyati', 'Xorazm Viloyati'],
    ],
  },
  VA: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '00120',
    zipex: '00120',
  },
  VC: {
    fmt: '%N%n%O%n%A%n%C %Z',
    zip: 'VC\\d{4}',
    zipex: 'VC0100',
  },
  VE: {
    fmt: '%N%n%O%n%A%n%C %Z, %S',
    require: 'ACS',
    upper: 'CS',
    zip: '\\d{4}',
    zipex: '1010',
    regionType: 'state',
    regions: [
      ['Amazonas', 'Amazonas'],
      ['Anzoátegui', 'Anzoátegui'],
      ['Apure', 'Apure'],
      ['Aragua', 'Aragua'],
      ['Barinas', 'Barinas'],
      ['Bolívar', 'Bolívar'],
      ['Carabobo', 'Carabobo'],
      ['Cojedes', 'Cojedes'],
      ['Delta Amacuro', 'Delta Amacuro'],
      ['Dependencias Federales', 'Dependencias Federales'],
      ['Distrito Federal', 'Distrito Federal'],
      ['Falcón', 'Falcón'],
      ['Guárico', 'Guárico'],
      ['Lara', 'Lara'],
      ['Mérida', 'Mérida'],
      ['Miranda', 'Miranda'],
      ['Monagas', 'Monagas'],
      ['Nueva Esparta', 'Nueva Esparta'],
      ['Portuguesa', 'Portuguesa'],
      ['Sucre', 'Sucre'],
      ['Táchira', 'Táchira'],
      ['Trujillo', 'Trujillo'],
      ['Vargas', 'Vargas'],
      ['Yaracuy', 'Yaracuy'],
      ['Zulia', 'Zulia'],
    ],
  },
  VG: {
    fmt: '%N%n%O%n%A%n%C%n%Z',
    require: 'A',
    zip: 'VG\\d{4}',
    zipex: 'VG1110',
  },
  VI: {
    fmt: '%N%n%O%n%A%n%C %S %Z',
    require: 'ACSZ',
    upper: 'ACNOS',
    zip: '(008(?:(?:[0-4]\\d)|(?:5[01])))(?:[ \\-](\\d{4}))?',
    zipex: '00802-1222',
    regionType: 'state',
    postalType: 'zip',
  },
  VN: {
    fmt: '%N%n%O%n%A%n%C%n%S %Z',
    lfmt: '%N%n%O%n%A%n%C%n%S %Z',
    require: 'AS',
    zip: '\\d{5}\\d?',
    zipex: '70010',
    regions: [
      ['An Giang', 'An Giang Province'],
      ['Bà Rịa–Vũng Tàu', 'Ba Ria-Vung Tau Province'],
      ['Bạc Liêu', 'Bac Lieu Province'],
      ['Bắc Giang', 'Bac Giang Province'],
      ['Bắc Kạn', 'Bac Kan Province'],
      ['Bắc Ninh', 'Bac Ninh Province'],
      ['Bến Tre', 'Ben Tre Province'],
      ['Bình Dương', 'Binh Duong Province'],
      ['Bình Định', 'Binh Dinh Province'],
      ['Bình Phước', 'Binh Phuoc Province'],
      ['Bình Thuận', 'Binh Thuan Province'],
      ['Cà Mau', 'Ca Mau Province'],
      ['Cao Bằng', 'Cao Bang Province'],
      ['Cần Thơ', 'Can Tho City'],
      ['Đà Nẵng', 'Da Nang City'],
      ['Đắk Lắk', 'Dak Lak Province'],
      ['Đăk Nông', 'Dak Nong Province'],
      ['Điện Biên', 'Dien Bien Province'],
      ['Đồng Nai', 'Dong Nai Province'],
      ['Đồng Tháp', 'Dong Thap Province'],
      ['Gia Lai', 'Gia Lai Province'],
      ['Hà Giang', 'Ha Giang Province'],
      ['Hà Nam', 'Ha Nam Province'],
      ['Hà Nội', 'Hanoi City'],
      ['Hà Tĩnh', 'Ha Tinh Province'],
      ['Hải Dương', 'Hai Duong Province'],
      ['Hải Phòng', 'Haiphong City'],
      ['Hậu Giang', 'Hau Giang Province'],
      ['Hòa Bình', 'Hoa Binh Province'],
      ['Hưng Yên', 'Hung Yen Province'],
      ['Khánh Hòa', 'Khanh Hoa Province'],
      ['Kiên Giang', 'Kien Giang Province'],
      ['Kon Tum', 'Kon Tum Province'],
      ['Lai Châu', 'Lai Chau Province'],
      ['Lạng Sơn', 'Lang Song Province'],
      ['Lào Cai', 'Lao Cai Province'],
      ['Lâm Đồng', 'Lam Dong Province'],
      ['Long An', 'Long An Province'],
      ['Nam Định', 'Nam Dinh Province'],
      ['Nghệ An', 'Nghe An Province'],
      ['Ninh Bình', 'Ninh Binh Province'],
      ['Ninh Thuận', 'Ninh Thuan Province'],
      ['Phú Thọ', 'Phu Tho Province'],
      ['Phú Yên', 'Phu Yen Province'],
      ['Quảng Bình', 'Quang Binh Province'],
      ['Quảng Nam', 'Quang Nam Province'],
      ['Quảng Ngãi', 'Quang Ngai Province'],
      ['Quảng Ninh', 'Quang Ninh Province'],
      ['Quảng Trị', 'Quang Tri Province'],
      ['Sóc Trăng', 'Soc Trang Province'],
      ['Sơn La', 'Son La Province'],
      ['Tây Ninh', 'Tay Ninh Province'],
      ['Thái Bình', 'Thai Binh Province'],
      ['Thái Nguyên', 'Thai Nguyen Province'],
      ['Thanh Hóa', 'Thanh Hoa Province'],
      ['Thành phố Hồ Chí Minh', 'Ho Chi Minh City'],
      ['Thành phố Huế', 'Hue City'],
      ['Tiền Giang', 'Tien Giang Province'],
      ['Trà Vinh', 'Tra Vinh Province'],
      ['Tuyên Quang', 'Tuyen Quang Province'],
      ['Vĩnh Long', 'Vinh Long Province'],
      ['Vĩnh Phúc', 'Vinh Phuc Province'],
      ['Yên Bái', 'Yen Bai Province'],
    ],
  },
  VU: {},
  WF: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '986\\d{2}',
    zipex: '98600',
  },
  WS: {},
  XK: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '[1-7]\\d{4}',
    zipex: '10000',
  },
  YE: {},
  YT: {
    fmt: '%O%n%N%n%A%n%Z %C %X',
    require: 'ACZ',
    upper: 'ACX',
    zip: '976\\d{2}',
    zipex: '97600',
  },
  ZA: {
    fmt: '%N%n%O%n%A%n%D%n%C%n%Z',
    require: 'ACZ',
    zip: '\\d{4}',
    zipex: '0083',
  },
  ZM: {
    fmt: '%N%n%O%n%A%n%Z %C',
    zip: '\\d{5}',
    zipex: '50100',
  },
  ZW: {},
  ZZ: {
    fmt: '%N%n%O%n%A%n%C',
    require: 'AC',
    upper: 'C',
    regionType: 'province',
    cityType: 'city',
    postalType: 'postal',
  },
};
